<a href="https://colab.research.google.com/drive/18rDYMg33f2vL8T6rpH-eiIo9OlROWjGN#scrollTo=f242c16b" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Selecting Data with Pandas

Data selection is one of the most fundamental and crucial skills in data analysis. Before you can clean, transform, or visualize your data, you need to know how to effectively access the specific parts of it that you're interested in. Pandas, a powerful Python library for data manipulation, provides numerous intuitive and flexible ways to select and filter data from DataFrames and Series. Mastering these techniques will significantly boost your efficiency and accuracy in any data-related task.

## 2. Learning Objectives

After completing this notebook, students should be able to:

*   Access DataFrame columns
*   Select one or multiple columns
*   Select rows using labels
*   Select rows using positions
*   Filter rows using conditions
*   Combine multiple conditions
*   Use `.loc`
*   Use `.iloc`
*   Use `.at`
*   Use `.iat`
*   Select subsets of rows and columns
*   Use Boolean indexing
*   Query data using `.query()`
*   Understand the differences between selection methods
*   Avoid common indexing mistakes

## 3. Import Libraries

First, let's import the necessary libraries: `pandas` for data manipulation and `numpy` for numerical operations, which we'll use to create our sample data.

In [1]:
import pandas as pd
import numpy as np

## 4. Create Sample Dataset

To practice data selection, we'll create a realistic employee dataset with various data types. This dataset will serve as our playground throughout this notebook.

In [2]:
data = {
    'EmployeeID': range(101, 121),
    'Name': [
        'Alice Smith', 'Bob Johnson', 'Charlie Brown', 'Diana Prince', 'Eve Adams',
        'Frank White', 'Grace Taylor', 'Harry Wilson', 'Ivy Davis', 'Jack Miller',
        'Karen Moore', 'Liam Hall', 'Mia Clark', 'Noah Lewis', 'Olivia King',
        'Paul Green', 'Quinn Baker', 'Rachel Scott', 'Steve Turner', 'Tina Wright'
    ],
    'Department': [
        'IT', 'HR', 'Finance', 'Marketing', 'IT',
        'Sales', 'HR', 'IT', 'Marketing', 'Finance',
        'IT', 'Sales', 'HR', 'Finance', 'Marketing',
        'Sales', 'IT', 'HR', 'Marketing', 'Sales'
    ],
    'Age': np.random.randint(25, 60, 20),
    'Gender': [
        'Female', 'Male', 'Male', 'Female', 'Female',
        'Male', 'Female', 'Male', 'Female', 'Male',
        'Female', 'Male', 'Female', 'Male', 'Female',
        'Male', 'Female', 'Female', 'Male', 'Female'
    ],
    'Salary': np.random.randint(45000, 120000, 20),
    'Experience': np.random.randint(1, 30, 20),
    'City': [
        'New York', 'London', 'Paris', 'Tokyo', 'Berlin',
        'New York', 'London', 'Paris', 'Tokyo', 'Berlin',
        'New York', 'London', 'Paris', 'Tokyo', 'Berlin',
        'New York', 'London', 'Paris', 'Tokyo', 'Berlin'
    ],
    'PerformanceScore': np.random.randint(60, 100, 20)
}

df = pd.DataFrame(data)

print("Sample Employee Dataset:")
display(df.head())

# Display basic info to check data types and non-null counts
print("\nDataFrame Info:")
df.info()

Sample Employee Dataset:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
1,102,Bob Johnson,HR,27,Male,66466,22,London,97
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70
3,104,Diana Prince,Marketing,40,Female,87388,3,Tokyo,60
4,105,Eve Adams,IT,46,Female,63182,24,Berlin,95

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        20 non-null     int64
 1   Name              20 non-null     object
 2   Department        20 non-null     object
 3   Age               20 non-null     int64
 4   Gender            20 non-null     object
 5   Salary            20 non-null     int64
 6   Experience        20 non-null     int64
 7   City              20 non-null     object
 8   PerformanceScore  20 non-null     int64
dtypes: int64(5), object(4)
memory usage: 1.5+ KB

## 5. Understanding DataFrame Structure

Before diving into selection, let's quickly recap the basic components of a Pandas DataFrame:

*   **Rows**: Horizontal entries in the DataFrame, representing individual observations or records (e.g., individual employees).
*   **Columns**: Vertical entries, representing different attributes or features of the data (e.g., 'Name', 'Department', 'Salary').
*   **Index**: A special label for each row, used for identification and selection. By default, it's a numerical sequence (0, 1, 2, ...), but it can be custom labels (e.g., EmployeeID, dates).

```
+-----------+--------------+------------+----------+
|   Index   |  Column 1    |  Column 2  | Column 3 |
+-----------+--------------+------------+----------+
|   Row 0   |    Value     |    Value   |   Value  |
|   Row 1   |    Value     |    Value   |   Value  |
|   Row 2   |    Value     |    Value   |   Value  |
+-----------+--------------+------------+----------+
```

## 6. Selecting Columns

Selecting columns is one of the most common operations. You can select a single column or multiple columns from a DataFrame.

### Selecting a Single Column

To select a single column, use square brackets `[]` with the column name as a string. This returns a Pandas Series.

In [3]:
# Selecting the 'Salary' column
salary_column = df["Salary"]
print("Type of selected column:", type(salary_column))
print("\nFirst 5 rows of Salary column:")
display(salary_column.head())

Type of selected column: <class 'pandas.core.series.Series'>

First 5 rows of Salary column:

0     65810
1     66466
2    110503
3     87388
4     63182
Name: Salary, dtype: int64

### Selecting Multiple Columns

To select multiple columns, pass a **list of column names** inside the square brackets. This returns a new DataFrame.

In [4]:
# Selecting 'Name' and 'Department' columns
name_department = df[["Name", "Department"]]
print("Type of selected columns:", type(name_department))
print("\nFirst 5 rows of Name and Department columns:")
display(name_department.head())

Type of selected columns: <class 'pandas.core.frame.DataFrame'>

First 5 rows of Name and Department columns:

            Name Department
0    Alice Smith         IT
1    Bob Johnson         HR
2  Charlie Brown    Finance
3   Diana Prince  Marketing
4      Eve Adams         IT

### Knowledge Check

1. What is the difference in data type when you select one column versus multiple columns?

## 7. Selecting Rows Using Labels (`.loc`)

The `.loc` accessor is used for **label-based indexing**. This means you use the actual row and column labels to make selections. It is inclusive of both the start and end of the slice.

### Selecting a Single Row by Label

To select a single row, use `.loc[row_label]`.

In [5]:
# Select the row with index label 3
row_3 = df.loc[3]
print("Row at index label 3:")
display(row_3)

Row at index label 3:

EmployeeID                   104
Name                Diana Prince
Department             Marketing
Age                           40
Gender                    Female
Salary                     87388
Experience                     3
City                       Tokyo
PerformanceScore              60
Name: 3, dtype: object

### Selecting Multiple Rows by Label (Slice)

Use slicing with row labels: `df.loc[start_label:end_label]`. Both `start_label` and `end_label` are included.

In [6]:
# Select rows from index label 2 to 6 (inclusive)
rows_2_to_6 = df.loc[2:6]
print("Rows from index label 2 to 6:")
display(rows_2_to_6)

Rows from index label 2 to 6:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70
3,104,Diana Prince,Marketing,40,Female,87388,3,Tokyo,60
4,105,Eve Adams,IT,46,Female,63182,24,Berlin,95
5,106,Frank White,Sales,43,Male,69434,21,New York,73
6,107,Grace Taylor,HR,59,Female,51670,19,London,73

### Selecting Specific Rows by Label (List)

Pass a list of specific row labels to select non-contiguous rows: `df.loc[[label1, label2, ...]]`.

In [7]:
# Select rows with index labels 1, 4, and 8
specific_rows = df.loc[[1, 4, 8]]
print("Specific rows with index labels 1, 4, 8:")
display(specific_rows)

Specific rows with index labels 1, 4, 8:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
1,102,Bob Johnson,HR,27,Male,66466,22,London,97
4,105,Eve Adams,IT,46,Female,63182,24,Berlin,95
8,109,Ivy Davis,Marketing,27,Female,51662,21,Tokyo,64

### Selecting Rows and Columns Together with `.loc`

You can specify both row and column labels using `df.loc[row_labels, column_labels]`.

In [8]:
# Select rows from 0 to 5 and columns 'Name' and 'Salary'
subset_loc = df.loc[0:5, ["Name", "Salary"]]
print("Subset using .loc:")
display(subset_loc)

Subset using .loc:

            Name  Salary
0    Alice Smith   65810
1    Bob Johnson   66466
2  Charlie Brown  110503
3   Diana Prince   87388
4      Eve Adams   63182
5    Frank White   69434

## 8. Selecting Rows Using Position (`.iloc`)

The `.iloc` accessor is used for **integer-location based indexing**. This means you use the integer position of rows and columns (0-based) to make selections. It is exclusive of the end of the slice (like standard Python list slicing).

### Selecting a Single Row by Position

To select a single row, use `df.iloc[row_position]`.

In [9]:
# Select the row at integer position 3 (the 4th row)
row_at_pos_3 = df.iloc[3]
print("Row at integer position 3:")
display(row_at_pos_3)

Row at integer position 3:

EmployeeID                   104
Name                Diana Prince
Department             Marketing
Age                           40
Gender                    Female
Salary                     87388
Experience                     3
City                       Tokyo
PerformanceScore              60
Name: 3, dtype: object

### Selecting Multiple Rows by Position (Slice)

Use slicing with integer positions: `df.iloc[start_pos:end_pos]`. Note that `end_pos` is *exclusive*.

In [10]:
# Select rows from integer position 2 up to (but not including) 6
rows_pos_2_to_5 = df.iloc[2:6]
print("Rows from integer position 2 to 5:")
display(rows_pos_2_to_5)

Rows from integer position 2 to 5:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70
3,104,Diana Prince,Marketing,40,Female,87388,3,Tokyo,60
4,105,Eve Adams,IT,46,Female,63182,24,Berlin,95
5,106,Frank White,Sales,43,Male,69434,21,New York,73

### Selecting Rows and Columns Together with `.iloc`

You can specify both row and column positions using `df.iloc[row_positions, column_positions]`.

In [11]:
# Select rows from position 1 up to (but not including) 6,
# and columns from position 2 up to (but not including) 5
subset_iloc = df.iloc[1:6, 2:5]
print("Subset using .iloc:")
display(subset_iloc)

Subset using .iloc:

  Department  Age  Gender
1         HR   27    Male
2    Finance   43    Male
3  Marketing   40  Female
4         IT   46  Female
5      Sales   43    Male

### Knowledge Check

1. If you wanted the first 10 rows of a DataFrame, how would you use `.loc` and `.iloc`? What would be the difference in the arguments you pass?

## 9. Difference Between `.loc` and `.iloc`

Understanding the distinction between `.loc` and `.iloc` is crucial for effective data selection in Pandas. Here's a comparison:

| Feature           | `.loc` (Label-based)                           | `.iloc` (Integer-location based)                 |
| :---------------- | :--------------------------------------------- | :----------------------------------------------- |
| **Indexing Type** | Uses actual row/column labels                  | Uses integer positions (0-based)                 |
| **Slicing End**   | **Inclusive** of the end label (`start:end` includes `end`) | **Exclusive** of the end position (`start:end` excludes `end`) |
| **Input Types**   | Labels (strings, numbers, datetimes, booleans) | Integers or lists/slices of integers             |
| **Use Case**      | When you know the specific labels of rows/columns you want | When you know the numerical positions of rows/columns you want |

Let's illustrate with examples:

In [12]:
# Example: Select a single element

# Using .loc (label for row index 5, label for column 'Salary')
print(f"Value at df.loc[5, 'Salary']: {df.loc[5, 'Salary']}")

# Using .iloc (integer position for row 5, integer position for 'Salary' column - let's assume it's 5th column index 4)
# First, find the integer position of 'Salary' column
salary_col_pos = df.columns.get_loc('Salary')
print(f"Value at df.iloc[5, {salary_col_pos}]: {df.iloc[5, salary_col_pos]}")

print("\n---")

# Example: Slicing rows

# Using .loc (inclusive)
print("Rows df.loc[0:2] (includes index 2):")
display(df.loc[0:2])

# Using .iloc (exclusive)
print("Rows df.iloc[0:2] (excludes index 2, so only 0 and 1):")
display(df.iloc[0:2])

print("\n---")

# Example: Slicing rows and columns

# Using .loc (inclusive for both row and column labels)
print("df.loc[0:1, ['Name', 'Department']] (includes row 1, includes Department column):")
display(df.loc[0:1, ['Name', 'Department']])

# Using .iloc (exclusive for both row and column positions)
# 'Name' is col 1 (index 1), 'Department' is col 2 (index 2)
print("df.iloc[0:2, 1:3] (excludes row 2, excludes column at index 3):")
display(df.iloc[0:2, 1:3])

Value at df.loc[5, 'Salary']: 69434
Value at df.iloc[5, 5]: 69434

---
Rows df.loc[0:2] (includes index 2):

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
1,102,Bob Johnson,HR,27,Male,66466,22,London,97
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70

Rows df.iloc[0:2] (excludes index 2, so only 0 and 1):

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
1,102,Bob Johnson,HR,27,Male,66466,22,London,97

---
df.loc[0:1, ['Name', 'Department']] (includes row 1, includes Department column):

          Name Department
0  Alice Smith         IT
1  Bob Johnson         HR

df.iloc[0:2, 1:3] (excludes row 2, excludes column at index 3):

          Name Department
0  Alice Smith         IT
1  Bob Johnson         HR

## 10. Fast Scalar Access (`.at` and `.iat`)

When you need to access a single value (scalar) in a DataFrame, `.at` and `.iat` provide faster access than `.loc` and `.iloc` respectively, especially for large DataFrames.

### `.at` (Label-based Scalar Access)

`.at` is used to get a single value by row label and column label.

In [13]:
# Get the salary of the employee at index label 3
salary_at_3 = df.at[3, "Salary"]
print(f"Salary of employee at index 3 using .at: {salary_at_3}")

Salary of employee at index 3 using .at: 87388

### `.iat` (Integer-location based Scalar Access)

`.iat` is used to get a single value by row integer position and column integer position.

In [14]:
# Get the value at row integer position 3 and column integer position 4 (Age column)
# Let's verify column position first: df.columns.get_loc('Age')
age_col_pos = df.columns.get_loc('Age')
age_at_3_4 = df.iat[3, age_col_pos]
print(f"Age of employee at row position 3 and column position {age_col_pos} (Age) using .iat: {age_at_3_4}")

Age of employee at row position 3 and column position 3 (Age) using .iat: 40

### When to use `.at` and `.iat`?

Use `.at` or `.iat` when you need to access or modify a **single cell** and performance is critical. For general selection of slices or multiple values, `.loc` and `.iloc` are more appropriate.

## 11. Boolean Indexing

Boolean indexing (also known as Boolean filtering) is a powerful way to select rows based on whether they meet specific conditions. You provide a Series of `True`/`False` values to the DataFrame, and only rows corresponding to `True` will be selected.

### Example: Employees older than 30

In [15]:
# Create a boolean Series
condition_age = df["Age"] > 30
print("Boolean Series for Age > 30:")
display(condition_age.head())

# Use the boolean Series to filter the DataFrame
employees_older_than_30 = df[condition_age]
print("\nEmployees older than 30:")
display(employees_older_than_30.head())

Boolean Series for Age > 30:

0     True
1    False
2     True
3     True
4     True
Name: Age, dtype: bool

Employees older than 30:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70
3,104,Diana Prince,Marketing,40,Female,87388,3,Tokyo,60
4,105,Eve Adams,IT,46,Female,63182,24,Berlin,95
5,106,Frank White,Sales,43,Male,69434,21,New York,73

### Example: Salary greater than 70000

In [16]:
high_salary_employees = df[df["Salary"] > 70000]
print("Employees with Salary > 70000:")
display(high_salary_employees.head())

Employees with Salary > 70000:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70
3,104,Diana Prince,Marketing,40,Female,87388,3,Tokyo,60
7,108,Harry Wilson,IT,46,Male,70578,12,Paris,87
10,111,Karen Moore,IT,27,Female,87934,11,New York,82
12,113,Mia Clark,HR,42,Female,119380,15,Paris,61

### Example: Department equals 'IT'

In [17]:
it_department_employees = df[df["Department"] == "IT"]
print("Employees in the IT Department:")
display(it_department_employees.head())

Employees in the IT Department:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
4,105,Eve Adams,IT,46,Female,63182,24,Berlin,95
7,108,Harry Wilson,IT,46,Male,70578,12,Paris,87
10,111,Karen Moore,IT,27,Female,87934,11,New York,82
16,117,Quinn Baker,IT,51,Female,78472,28,London,69

### Example: City equals 'New York'

In [18]:
ny_employees = df[df["City"] == "New York"]
print("Employees living in New York:")
display(ny_employees.head())

Employees living in New York:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
5,106,Frank White,Sales,43,Male,69434,21,New York,73
10,111,Karen Moore,IT,27,Female,87934,11,New York,82
15,116,Paul Green,Sales,54,Male,90968,21,New York,99

### Example: Experience greater than 5 years

In [19]:
experienced_employees = df[df["Experience"] > 5]
print("Employees with more than 5 years of experience:")
display(experienced_employees.head())

Employees with more than 5 years of experience:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
1,102,Bob Johnson,HR,27,Male,66466,22,London,97
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70
4,105,Eve Adams,IT,46,Female,63182,24,Berlin,95
5,106,Frank White,Sales,43,Male,69434,21,New York,73
6,107,Grace Taylor,HR,59,Female,51670,19,London,73

## 12. Multiple Conditions

You can combine multiple boolean conditions using logical operators. **Crucially, each condition must be enclosed in parentheses.**

*   **AND (`&`)**: Both conditions must be `True`.
*   **OR (`|`)**: At least one condition must be `True`.
*   **NOT (`~`)**: Negates a condition (flips `True` to `False` and vice versa).

### Example: Employees older than 30 AND salary greater than 70000

In [20]:
senior_high_earners = df[(df["Age"] > 30) & (df["Salary"] > 70000)]
print("Employees older than 30 AND salary > 70000:")
display(senior_high_earners.head())

Employees older than 30 AND salary > 70000:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70
3,104,Diana Prince,Marketing,40,Female,87388,3,Tokyo,60
7,108,Harry Wilson,IT,46,Male,70578,12,Paris,87
12,113,Mia Clark,HR,42,Female,119380,15,Paris,61
13,114,Noah Lewis,Finance,33,Male,95609,24,Tokyo,90

### Example: Employees in IT OR HR department

In [21]:
it_or_hr_employees = df[(df["Department"] == "IT") | (df["Department"] == "HR")]
print("Employees in IT OR HR department:")
display(it_or_hr_employees.head())

Employees in IT OR HR department:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
1,102,Bob Johnson,HR,27,Male,66466,22,London,97
4,105,Eve Adams,IT,46,Female,63182,24,Berlin,95
6,107,Grace Taylor,HR,59,Female,51670,19,London,73
7,108,Harry Wilson,IT,46,Male,70578,12,Paris,87

### Example: Employees NOT in the IT department

In [22]:
not_it_employees = df[~(df["Department"] == "IT")]
print("Employees NOT in the IT department:")
display(not_it_employees.head())

Employees NOT in the IT department:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
1,102,Bob Johnson,HR,27,Male,66466,22,London,97
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70
3,104,Diana Prince,Marketing,40,Female,87388,3,Tokyo,60
5,106,Frank White,Sales,43,Male,69434,21,New York,73
6,107,Grace Taylor,HR,59,Female,51670,19,London,73

### Importance of Parentheses

Parentheses are essential because of Python's operator precedence. Without them, the `&` and `|` operators would be evaluated before the comparison operators (`>`, `==`, etc.), leading to errors or incorrect results.

### Knowledge Check

1. Write a condition to find all female employees who are in the Marketing department and have a performance score above 85.

## 13. Using `isin()`

The `.isin()` method is a convenient way to filter a DataFrame when you want to select rows where a column's value is one of several possibilities. It's much cleaner than using multiple `OR` conditions.

In [23]:
# Select employees whose department is either 'IT' or 'HR'
employees_in_it_or_hr_isin = df[df["Department"].isin(["IT", "HR"])]
print("Employees in IT or HR using .isin():")
display(employees_in_it_or_hr_isin.head())

Employees in IT or HR using .isin():

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
1,102,Bob Johnson,HR,27,Male,66466,22,London,97
4,105,Eve Adams,IT,46,Female,63182,24,Berlin,95
6,107,Grace Taylor,HR,59,Female,51670,19,London,73
7,108,Harry Wilson,IT,46,Male,70578,12,Paris,87

### Practical Applications

*   **Filtering by categories**: Easily select data belonging to a predefined set of categories (e.g., specific product types, regions).
*   **Excluding values**: Combine with `~` (NOT) to exclude certain values (e.g., `df[~df['Status'].isin(['Retired', 'Terminated'])]`).

## 14. Using `between()`

The `.between()` method is used to select rows where a numeric column's value falls within a specified range (inclusive).

In [24]:
# Select employees with salary between 50000 and 80000 (inclusive)
salary_range_employees = df[df["Salary"].between(50000, 80000)]
print("Employees with Salary between 50000 and 80000:")
display(salary_range_employees.head())

Employees with Salary between 50000 and 80000:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
1,102,Bob Johnson,HR,27,Male,66466,22,London,97
4,105,Eve Adams,IT,46,Female,63182,24,Berlin,95
5,106,Frank White,Sales,43,Male,69434,21,New York,73
6,107,Grace Taylor,HR,59,Female,51670,19,London,73

## 15. String Filtering

Pandas provides a `.str` accessor for Series that contain string data, allowing you to perform string-specific operations for filtering.

### `str.startswith()`

Selects rows where the string in a column starts with a specified prefix.

In [25]:
# Select employees whose names start with 'A'
names_start_a = df[df["Name"].str.startswith("A")]
print("Employees whose names start with 'A':")
display(names_start_a)

Employees whose names start with 'A':

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81

### `str.endswith()`

Selects rows where the string in a column ends with a specified suffix.

In [26]:
# Select employees whose names end with 'n'
names_end_n = df[df["Name"].str.endswith("n")]
print("Employees whose names end with 'n':")
display(names_end_n)

Employees whose names end with 'n':

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
1,102,Bob Johnson,HR,27,Male,66466,22,London,97
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70
7,108,Harry Wilson,IT,46,Male,70578,12,Paris,87
15,116,Paul Green,Sales,54,Male,90968,21,New York,99

### `str.contains()`

Selects rows where the string in a column contains a specified substring. You can also use regular expressions.

In [27]:
# Select employees whose city name contains 'New'
city_contains_new = df[df["City"].str.contains("New", case=False)] # case=False for case-insensitive search
print("Employees whose city name contains 'New':")
display(city_contains_new)

Employees whose city name contains 'New':

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
5,106,Frank White,Sales,43,Male,69434,21,New York,73
10,111,Karen Moore,IT,27,Female,87934,11,New York,82
15,116,Paul Green,Sales,54,Male,90968,21,New York,99

### Knowledge Check

1. How would you select all employees whose department name contains the letter 'i' (case-insensitive)?

## 16. Common Mistakes

Even experienced users can sometimes trip up on Pandas indexing. Being aware of these common pitfalls can save you time and frustration.

### Mistake 1: Using parentheses instead of square brackets for column selection

Pandas uses square brackets `[]` for column selection, not parentheses `()`.

In [33]:
# Incorrect way
# try:
#     df("Name")
# except TypeError as e:
#     print(f"Error: {e}")

# Correct way
correct_name_selection = df["Name"]
print("Correct column selection:")
display(correct_name_selection.head())

Correct column selection:

0      Alice Smith
1      Bob Johnson
2    Charlie Brown
3     Diana Prince
4        Eve Adams
Name: Name, dtype: object

### Mistake 2: Forgetting parentheses around Boolean conditions

When combining multiple conditions with `&` or `|`, each individual condition must be wrapped in parentheses.

In [34]:
# Incorrect way (will raise ValueError due to operator precedence)
# try:
#     df[df["Age"] > 30 & df["Department"] == "IT"]
# except ValueError as e:
#     print(f"Error: {e}")

# Correct way
correct_multi_condition = df[(df["Age"] > 30) & (df["Department"] == "IT")]
print("Correct multiple conditions selection:")
display(correct_multi_condition.head())

Correct multiple conditions selection:

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
4,105,Eve Adams,IT,46,Female,63182,24,Berlin,95
7,108,Harry Wilson,IT,46,Male,70578,12,Paris,87
16,117,Quinn Baker,IT,51,Female,78472,28,London,69

### Mistake 3: Confusing `.loc` and `.iloc` (especially with slicing)

Remember `.loc` is label-inclusive, `.iloc` is position-exclusive for the end of the slice.

In [35]:
# If you want rows with index labels 0, 1, 2:
print("Using .loc[0:2] (inclusive of label 2):")
display(df.loc[0:2])

# If you want rows at integer positions 0, 1, 2:
print("Using .iloc[0:3] (exclusive of position 3):")
display(df.iloc[0:3])

Using .loc[0:2] (inclusive of label 2):

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
1,102,Bob Johnson,HR,27,Male,66466,22,London,97
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70

Using .iloc[0:3] (exclusive of position 3):

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,49,Female,65810,5,New York,81
1,102,Bob Johnson,HR,27,Male,66466,22,London,97
2,103,Charlie Brown,Finance,43,Male,110503,22,Paris,70

### Mistake 4: Selecting multiple columns incorrectly

When selecting multiple columns, you must pass a *list* of column names inside the square brackets, not just comma-separated strings.

In [36]:
# Incorrect way (will raise a KeyError)
# try:
#     df["Name", "Department"]
# except KeyError as e:
#     print(f"Error: {e} - Expected a list of column names for multiple selection")

# Correct way
correct_multi_column = df[["Name", "Department"]]
print("Correct multiple column selection:")
display(correct_multi_column.head())

Correct multiple column selection:

            Name Department
0    Alice Smith         IT
1    Bob Johnson         HR
2  Charlie Brown    Finance
3   Diana Prince  Marketing
4      Eve Adams         IT

### Knowledge Check

1. Explain why `df[df['Age'] > 30 and df['Salary'] > 70000]` would likely fail, and how to correct it.

## 19. Summary Table

Here's a quick reference for common data selection tasks:

| Task                 | Method                               | Description                                        |
| :------------------- | :----------------------------------- | :------------------------------------------------- |
| **One Column**       | `df["col_name"]`                     | Returns a Series                                   |
| **Multiple Columns** | `df[["col_A","col_B"]]`              | Returns a DataFrame                                |
| **Row by Label**     | `df.loc[row_label]`                  | Returns a Series (row as an observation)           |
| **Rows by Label**    | `df.loc[start_label:end_label]`      | Returns a DataFrame (inclusive end)                |
| **Row by Position**  | `df.iloc[row_pos]`                   | Returns a Series (row as an observation)           |
| **Rows by Position** | `df.iloc[start_pos:end_pos]`         | Returns a DataFrame (exclusive end)                |
| **Scalar by Label**  | `df.at[row_label, col_label]`        | Fastest way to access a single value by label      |
| **Scalar by Position** | `df.iat[row_pos, col_pos]`         | Fastest way to access a single value by position   |
| **Boolean Filtering**| `df[df["col"] > value]`              | Select rows based on a condition                   |
| **Multiple Conditions**| `df[(cond1) & (cond2)]`              | Combine conditions using `&`, `|`, `~` (with parentheses) |
| **Values in List**   | `df[df["col"].isin([val1, val2])]`  | Select rows where column value is in a list        |
| **Values in Range**  | `df[df["col"].between(lower, upper)]`| Select rows where column value is in a numeric range |
| **String Starts With**| `df[df["col"].str.startswith("P")]`| Select rows where string starts with a prefix      |
| **String Contains**  | `df[df["col"].str.contains("sub")]`| Select rows where string contains a substring      |

## 20. Practice Exercises

Now it's your turn! Use the `df` DataFrame created earlier to solve the following problems. Try to use the most appropriate selection method for each task. Do not peek at solutions yet!

1.  Select only the 'Name' and 'Salary' columns of the DataFrame.
2.  Get the 'Department' column as a Series.
3.  Retrieve the row with index label 7 using `.loc`.
4.  Retrieve the 5th row (index position 4) using `.iloc`.
5.  Select rows with index labels 10, 12, and 15.
6.  Select rows from integer position 0 to 9 (inclusive).
7.  Extract the 'EmployeeID' and 'Age' for rows with index labels from 5 to 10 (inclusive) using `.loc`.
8.  Extract the 'Name', 'Department', and 'Salary' for rows at integer positions 8 to 12 (inclusive).
9.  Find the 'PerformanceScore' of the employee at index label 0 using `.at`.
10. Find the 'Gender' of the employee at integer row position 14 (assuming 'Gender' is the 5th column, index 4) using `.iat`.
11. Select all employees who are 'Female'.
12. Find all employees whose 'Salary' is less than 60000.
13. Select employees who have 'Experience' greater than 10 years.
14. Find all employees who are 'Male' AND work in the 'Sales' department.
15. Select employees whose 'Age' is between 30 and 40 (inclusive).
16. Find employees who work in 'IT', 'Finance', or 'Marketing' departments using `isin()`.
17. Select employees whose 'Name' starts with 'S'.
18. Select employees whose 'City' contains 'on' (case-insensitive) using `str.contains()`.

## 21. Final Notes

Congratulations! You've covered the essential techniques for selecting data in Pandas. This skill is foundational to almost every data analysis task.

### Key Concepts:

*   **Column Selection**: Use `[]` for single (Series) or multiple columns (`[[]]` for DataFrame).
*   **Label-based vs. Position-based**: Understand when to use `.loc` (labels, inclusive) and `.iloc` (integer positions, exclusive).
*   **Scalar Access**: Use `.at` and `.iat` for fast single-value retrieval.
*   **Boolean Indexing**: Powerful for filtering rows based on conditions. Remember parentheses for multiple conditions.
*   **Helper Methods**: Leverage `isin()`, `between()`, and `.str` accessors for specific filtering needs.
*   **Query Method**: A readable alternative for complex string-based filtering.
*   **Random Sampling**: Use `.sample()` for random subsets.

Mastering data selection allows you to isolate, examine, and manipulate precisely the data you need, paving the way for more advanced operations like grouping, aggregation, visualization, and preparing data for machine learning models. Keep practicing, and these methods will become second nature!