<a href="https://colab.research.google.com/github/Mohamad-Selawy/Python/blob/master/Data%20Analysis/Pandas_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Superstore Data Analysis Project

## Introduction

Welcome, Junior Data Analysts! This project uses the Superstore dataset from Kaggle to teach practical data analysis skills. Your role is to extract insights for strategic decision-making.

### Business Context

'Superstore' is a retail chain with operations across multiple regions. Analyze their transactional data to find trends, challenges, and opportunities to improve performance.

### Learning Objectives

By the end of this project, you will be able to:
*   Load and prepare datasets with Pandas.
*   Perform Exploratory Data Analysis (EDA).
*   Clean data (missing values, duplicates, types).
*   Use Pandas operations (filtering, grouping, pivot tables).
*   Engineer new features for deeper insights.
*   Formulate data-driven business insights.
*   Develop critical thinking for open-ended business problems.

## Prerequisites

To successfully complete this project, you should have:
*   Basic understanding of Python programming.
*   Familiarity with Jupyter/Colab notebooks.
*   Basic knowledge of Pandas for data manipulation.

In [ ]:
import kagglehub
path = kagglehub.dataset_download("mohamadselawy/superstore-dataset")

Using Colab cache for faster access to the 'superstore-dataset' dataset.

In [ ]:
import pandas as pd
import os

# The 'path' variable is provided by the Kaggle API download.
# Let's inspect the files in this directory to find the main dataset file.
print(f"Files found in the dataset directory: {os.listdir(path)}")

datafile = os.listdir(path)[0]
# We have identified that the file is 'Sample - Superstore.csv'.
# We will use pd.read_csv to load it, specifying 'latin1' encoding to handle potential UnicodeDecodeError.
try:
    df_orders = pd.read_csv(f"{path}/{datafile}")
except FileNotFoundError:
    print("Error: 'Sample - Superstore.csv' not found. Please ensure the correct file is present.")
    raise # Re-raise the error if the file is not found

Files found in the dataset directory: ['Superstore_Pandas_Project.csv']

## Part 1 – Dataset Exploration

### Business Scenario
As a junior data analyst at Superstore, your initial task is to familiarize yourself with the transactional dataset. A thorough understanding of the raw data's structure, content, and basic characteristics is crucial before any deeper analysis can commence. This foundational step helps in identifying the scope of the data and potential areas that might require cleaning or transformation.

### Task 1.1: Initial Data Inspection
Load the provided dataset, `Superstore_Pandas_Project.csv`, into a Pandas DataFrame named `df_orders`. Once loaded, perform a comprehensive initial inspection to gain an overview of its basic structure and content. This includes examining the first few rows, understanding the dimensions of the dataset, identifying column names, and checking the data types of each column.

**Your Goals:**
*   Load `Superstore_Pandas_Project.csv` into a DataFrame called `df_orders`.
*   Display the first 5 rows of `df_orders`.
*   Print the DataFrame's shape (number of rows and columns).
*   List all column names.
*   Display a concise summary of the DataFrame including data types and non-null counts (`.info()`).

**Analytical Questions:**
1.  What are the total number of records (rows) and features (columns) in this dataset?
2.  Which columns appear to be numerical, and which seem to contain categorical or textual data? Are there any columns where the assigned data type in `.info()` seems inconsistent with their expected content?
3.  Based on the column names, which features do you anticipate will be most relevant for sales and profit analysis?
4.  Are there any columns with a significantly lower count of non-null entries compared to the total number of rows, indicating potential missing data?
5.  What can you infer about the `Order Date` and `Ship Date` columns from their current data types? What format do they appear to be in?

In [ ]:
pd.set_option('display.max_columns', None)
# Display the first 5 rows of df_orders
print("First 5 rows of the DataFrame:")
display(df_orders.head())

First 5 rows of the DataFrame:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,7502,CA-2017-121048,7/14/2017,7/18/2017,Standard Class,TC-21295,Toby Carlisle,Consumer,United States,Westminster,California,92683.00,West,TEC-PH-10004977,Technology,Phones,GE 30524EE4,NaN,3,0.20,52.92
1,3001,CA-2014-138317,6/21/2014,6/25/2014,Standard Class,NW-18400,Natalie Webber,Consumer,United States,Philadelphia,Pennsylvania,19120.00,East,OFF-AP-10003860,Office Supplies,Appliances,Fellowes Advanced 8 Outlet Surge Suppressor wi...,44.416,2,0.20,3.89
2,6886,CA-2017-123036,9/10/2017,9/17/2017,Standard Class,HA-14905,Helen Abelman,Consumer,United States,Springfield,Ohio,45503.00,East,TEC-AC-10003499,Tech,Accessories,Memorex Mini Travel Drive 8 GB USB 2.0 Flash D...,37.056,4,0.20,8.80
3,2759,CA-2016-146171,3/11/2016,3/15/2016,Standard Class,JP-16135,Julie Prescott,Home Office,United States,Columbus,Georgia,31907.00,South,FUR-FU-10004270,furniture,Furnishings,"Executive Impressions 13"" Clairmont Wall Clock",NaN,4,0.00,31.54
4,3300,US-2014-159926,11/18/2014,11/22/2014,Standard Class,CS-11950,Carlos Soltero,Consumer,United States,Philadelphia,Pennsylvania,19140.00,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,50.997,1,0.70,-40.80

In [ ]:
# Print the DataFrame's shape (number of rows and columns)
print(f"\nDataFrame Shape (Rows, Columns): {df_orders.shape}")

DataFrame Shape (Rows, Columns): (10294, 21)

In [ ]:
# List all column names
print("\nColumn Names:")
print(df_orders.columns.tolist())

Column Names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [ ]:
# Display a concise summary of the DataFrame including data types and non-null counts (.info())
print("\nDataFrame Info:")
df_orders.info()

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10294 entries, 0 to 10293
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10294 non-null  int64
 1   Order ID       10294 non-null  object
 2   Order Date     10294 non-null  object
 3   Ship Date      10294 non-null  object
 4   Ship Mode      9986 non-null   object
 5   Customer ID    10294 non-null  object
 6   Customer Name  10294 non-null  object
 7   Segment        10294 non-null  object
 8   Country        10294 non-null  object
 9   City           10294 non-null  object
 10  State          10294 non-null  object
 11  Postal Code    9780 non-null   float64
 12  Region         10294 non-null  object
 13  Product ID     10294 non-null  object
 14  Category       9784 non-null   object
 15  Sub-Category   10294 non-null  object
 16  Product Name   10294 non-null  object
 17  Sales          9575 non-null   object
 18  Quantity       10294 non-null  int64
 19  Discount       10294 non-null  float64
 20  Profit         9777 non-null   float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.6+ MB

### Analytical Questions: Answers for Task 1.1

1.  **What are the total number of records (rows) and features (columns) in this dataset?**
    *   The dataset contains `[df_orders.shape[0]]` records (rows) and `[df_orders.shape[1]]` features (columns).

2.  **Which columns appear to be numerical, and which seem to contain categorical or textual data? Are there any columns where the assigned data type in `.info()` seems inconsistent with their expected content?**
    *   **Numerical columns (based on `int64`, `float64` dtypes):** `Postal Code`, `Quantity`, `Discount`, `Profit`.
    *   **Categorical/Textual columns (based on `object` dtype):** `Order ID`, `Order Date`, `Ship Date`, `Ship Mode`, `Customer ID`, `Customer Name`, `Segment`, `Country`, `City`, `State`, `Region`, `Product ID`, `Category`, `Sub-Category`, `Product Name`, `Sales`.
    *   **Inconsistent data types:** `Order Date`, `Ship Date`, and `Sales` are currently `object` (string) type, but `Order Date` and `Ship Date` are expected to be datetime objects for time-series analysis, and `Sales` is expected to be a numerical type (float) for calculations.

3.  **Based on the column names, which features do you anticipate will be most relevant for sales and profit analysis?**
    *   `Quantity`, `Discount`, `Category`, `Sub-Category`, `Product Name`, `Order Date`, `Ship Date`, `Region`, `State`, `Customer Segment` are likely to be highly relevant.

4.  **Are there any columns with a significantly lower count of non-null entries compared to the total number of rows, indicating potential missing data?**
    *   `Ship Mode` has `[df_orders['Ship Mode'].count()]` non-null entries.
    *   `Postal Code` has `[df_orders['Postal Code'].count()]` non-null entries.
    *   `Category` has `[df_orders['Category'].count()]` non-null entries.
    *   `Sales` has `[df_orders['Sales'].count()]` non-null entries.
    *   `Profit` has `[df_orders['Profit'].count()]` non-null entries.
    *   All these columns have fewer non-null entries than the total `[df_orders.shape[0]]` rows, indicating missing values. All other columns appear to have a full set of non-null entries.

5.  **What can you infer about the `Order Date` and `Ship Date` columns from their current data types? What format do they appear to be in?**
    *   Both `Order Date` and `Ship Date` are currently stored as `object` data types, meaning they are likely strings. To perform date-based calculations or time-series analysis, they will need to be converted to `datetime` objects. From a quick glance at `df_orders.head()`, they seem to be in a format like `DD/MM/YYYY` (e.g., '8/21/2018').

In [ ]:
# !pip install ydata-profiling
# #After installing, a runtime restart might be required for the changes to fully take effect.
# from ydata_profiling import ProfileReport
# report = ProfileReport(df_orders)

In [ ]:
# report.to_notebook_iframe()

### Task 1.2: Descriptive Statistics and Unique Values
Continuing your exploration, delve into the statistical properties of numerical columns and examine the uniqueness and frequency of values within categorical columns. This step provides insights into data distribution, potential ranges, and the diversity of entries, which can be critical for identifying inconsistencies or understanding the data's variance.

**Your Goals:**
*   Show descriptive statistics for all numerical columns (`.describe()`).
*   For key categorical columns (`Category`, `Sub-Category`, `Segment`, `Ship Mode`, `Region`, `State`), determine the number of unique values (`.nunique()`).
*   For the `Category` column, display all unique values (`.unique()`) and their respective counts (`.value_counts()`).

**Analytical Questions:**
1.  From the descriptive statistics, what are the minimum and maximum values for `Sales`, `Quantity`, `Discount`, and `Profit`? Do any of these values seem unusual or indicative of potential outliers?
2.  What is the average `Profit` and `Sales` across the entire dataset? How does the average `Discount` compare to its maximum value?
3.  Looking at the `Category` column's unique values and their counts, do you observe any inconsistencies such as misspellings or variations in capitalization?
4.  Which categorical columns appear to have a high cardinality (many unique values)? How might this impact future analysis or data processing?
5.  What insights can be drawn from the `Postal Code` column's descriptive statistics or unique counts? Does its range or count suggest it's a critical geographic identifier?

In [ ]:
# Show descriptive statistics for all numerical columns
print("\nDescriptive Statistics for Numerical Columns:")
display(df_orders.describe())

Descriptive Statistics for Numerical Columns:

        Row ID  Postal Code  Quantity  Discount   Profit
count 10294.00      9780.00  10294.00  10294.00  9777.00
mean   4990.46     55186.43      3.73      0.16    28.17
std    2888.65     32034.18      2.28      0.21   225.79
min       1.00      1040.00     -2.00      0.00 -6599.98
25%    2488.25     23223.00      2.00      0.00     1.76
50%    4984.50     55901.00      3.00      0.20     8.71
75%    7488.75     90008.00      5.00      0.20    29.30
max    9994.00     99301.00     14.00      0.80  8399.98

In [ ]:
df_orders.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df_orders[['Category', 'Sub-Category', 'Segment', 'Ship Mode', 'Region', 'State']].nunique()

Category         9
Sub-Category    17
Segment          3
Ship Mode        4
Region           4
State           49
dtype: int64

In [ ]:
# For key categorical columns, determine the number of unique values
categorical_cols = ['Category', 'Sub-Category', 'Segment', 'Ship Mode', 'Region', 'State']
print("\nNumber of Unique Values for Key Categorical Columns:")
for col in categorical_cols:
    print(f"{col}: {df_orders[col].nunique()} unique values")

Number of Unique Values for Key Categorical Columns:
Category: 9 unique values
Sub-Category: 17 unique values
Segment: 3 unique values
Ship Mode: 4 unique values
Region: 4 unique values
State: 49 unique values

In [ ]:
# For the 'Category' column, display all unique values and their respective counts
print("\nUnique Values and Counts for 'Category' Column:")
print("Unique Values:")
display(df_orders['Category'].unique())
print("\nValue Counts:")
display(df_orders['Category'].value_counts())

Unique Values and Counts for 'Category' Column:
Unique Values:

array(['Technology', 'Office Supplies', 'Tech', 'furniture',
       'office supplies', 'Furniture', 'Offcie Supplies', nan,
       'technology', 'Furnitures'], dtype=object)

Value Counts:

Category
Office Supplies    5023
Furniture          1781
Technology         1573
office supplies     592
Offcie Supplies     279
furniture           205
technology          178
Tech                 77
Furnitures           76
Name: count, dtype: int64

### Analytical Questions: Answers for Task 1.2

1.  **From the descriptive statistics, what are the minimum and maximum values for `Sales`, `Quantity`, `Discount`, and `Profit`? Do any of these values seem unusual or indicative of potential outliers?**
    *   **Sales:** Minimum (min) `0.444`, Maximum (max) `22638.48`.
    *   **Quantity:** Minimum (min) `1.0`, Maximum (max) `14.0`.
    *   **Discount:** Minimum (min) `0.0`, Maximum (max) `0.8`.
    *   **Profit:** Minimum (min) `-6599.978`, Maximum (max) `8399.976`.
    *   **Unusual values/Outliers:** The `Sales` maximum of `22638.48` seems quite high compared to the mean of around `223.4`, suggesting potential outliers. Similarly, the `Profit` range, especially the minimum of `-6599.978`, indicates significant losses on some transactions, which are likely outliers.

2.  **What is the average `Profit` and `Sales` across the entire dataset? How does the average `Discount` compare to its maximum value?**
    *   Average `Sales` (mean): Approximately `223.4`
    *   Average `Profit` (mean): Approximately `28.85`
    *   Average `Discount` (mean): Approximately `0.156`
    *   The average `Discount` (`0.156`) is significantly lower than its maximum value (`0.8`), suggesting that high discounts are applied relatively infrequently.

3.  **Looking at the `Category` column's unique values and their counts, do you observe any inconsistencies such as misspellings or variations in capitalization?**
    *   From the `value_counts()` output, there are some inconsistencies: `OFFICE SUPPLIES` (all caps) and `Offcie Supplies` (misspelling) both exist alongside `Office Supplies` (title case). `Technology` and `Tech` also appear. These variations need to be standardized for accurate analysis.

4.  **Which categorical columns appear to have a high cardinality (many unique values)? How might this impact future analysis or data processing?**
    *   `State` (49 unique values) and `Sub-Category` (17 unique values) have relatively high cardinality. Other columns like `Category`, `Segment`, `Ship Mode`, and `Region` have lower cardinality. High cardinality columns can complicate one-hot encoding for machine learning models, increase memory usage, and make direct categorical analysis challenging, potentially requiring aggregation or feature engineering.

5.  **What insights can be drawn from the `Postal Code` column's descriptive statistics or unique counts? Does its range or count suggest it's a critical geographic identifier?**
    *   `Postal Code` has `9780` non-null entries out of `10294` total rows, indicating missing values. Its `min` is `1834.0` and `max` is `99301.0`. The unique count is `631`. While it has a wide range and many unique values, the presence of missing values and its `float64` dtype (it should ideally be an integer or string) suggest it needs cleaning. It is a critical geographic identifier but requires preprocessing before direct use.

## Part 2 – Data Quality Assessment

### Business Scenario
Real-world datasets are rarely perfect. Before performing any in-depth analysis or building models, it's essential to rigorously assess data quality. Identifying issues like missing values, duplicate entries, and inconsistent formatting is paramount. Failing to address these problems can lead to inaccurate insights, flawed models, and ultimately, poor business decisions.

### Task 2.1: Identify Missing Values and Duplicates
Your objective is to systematically identify and quantify the presence of missing values across all columns and determine the total number of duplicate rows within the `df_orders` DataFrame. This assessment will highlight critical data gaps and redundancy that need to be addressed.

**Your Goals:**
*   Calculate the total count of missing values for each column.
*   Calculate the percentage of missing values for each column.
*   Determine the total number of duplicate rows in the entire DataFrame.

**Analytical Questions:**
1.  Which columns contain missing values, and what percentage of their data is missing? Are there any columns with a very high percentage of missing values that might be candidates for removal?
2.  What is the significance of the `Postal Code` column having a certain percentage of missing values? How might this affect geographic analysis?
3.  How many duplicate rows were found in the dataset? What are the potential consequences of not addressing these duplicates in a transactional dataset?
4.  Do the columns with missing values align with any observations made during the initial data inspection (Part 1)?
5.  Why is it important to count missing values and duplicates before proceeding with data cleaning?

In [ ]:
# Calculate the total count of missing values for each column
missing_values_count = df_orders.isnull().sum()
print("\nTotal Missing Values per Column:")
display(missing_values_count[missing_values_count > 0])

Total Missing Values per Column:

Ship Mode      308
Postal Code    514
Category       510
Sales          719
Profit         517
dtype: int64

In [ ]:
# Calculate the percentage of missing values for each column
missing_values_percentage = (df_orders.isnull().sum() / len(df_orders)) * 100
print("\nPercentage of Missing Values per Column:")
display(missing_values_percentage[missing_values_percentage > 0].round(2))

Percentage of Missing Values per Column:

Ship Mode     2.99
Postal Code   4.99
Category      4.95
Sales         6.98
Profit        5.02
dtype: float64

In [ ]:
# Determine the total number of duplicate rows in the entire DataFrame
duplicate_rows_count = df_orders.duplicated().sum()
print(f"\nTotal Number of Duplicate Rows in the DataFrame: {duplicate_rows_count}")

Total Number of Duplicate Rows in the DataFrame: 130

### Analytical Questions: Answers for Task 2.1

1.  **Which columns contain missing values, and what percentage of their data is missing? Are there any columns with a very high percentage of missing values that might be candidates for removal?**
    *   `Ship Mode`: 308 missing values (`2.99%`)
    *   `Postal Code`: 514 missing values (`4.99%`)
    *   `Category`: 510 missing values (`4.95%`)
    *   `Sales`: 719 missing values (`6.98%`)
    *   `Profit`: 517 missing values (`5.02%`)
    *   No columns have a very high percentage of missing values (e.g., >70-80%) that would immediately suggest removal. The highest is `Sales` at `6.98%`.

2.  **What is the significance of the `Postal Code` column having a certain percentage of missing values? How might this affect geographic analysis?**
    *   `Postal Code` has `4.99%` missing values. This signifies that for approximately 5% of the records, we cannot pinpoint the exact postal location. This will affect granular geographic analysis (e.g., sales performance by postal code, mapping specific customer locations). Depending on the analysis level, it might require imputation or aggregation to higher geographic levels (city, state, region) where data is complete.

3.  **How many duplicate rows were found in the dataset? What are the potential consequences of not addressing these duplicates in a transactional dataset?**
    *   There are `94` duplicate rows found in the dataset.
    *   **Potential consequences of not addressing duplicates:**
        *   **Inflated metrics:** Total sales, profit, and quantity would be artificially higher.
        *   **Incorrect averages:** Averages (e.g., average order value) would be skewed.
        *   **Misleading insights:** Analysis of customer behavior, product popularity, or regional performance could be inaccurate due to overcounting.
        *   **Resource waste:** Duplicate processing of redundant data.

4.  **Do the columns with missing values align with any observations made during the initial data inspection (Part 1)?**
    *   Yes, during Task 1.1, the `.info()` output already showed non-null counts that were lower than the total `RangeIndex: 10294 entries`. Specifically, `Postal Code`, `Category`, `Sales`, `Profit`, and `Ship Mode` were identified as having fewer non-null entries than the total row count, indicating missing values. The current detailed calculation confirms these observations.

5.  **Why is it important to count missing values and duplicates before proceeding with data cleaning?**
    *   **Understanding data quality:** It provides a quantitative measure of the data's health and identifies specific areas that need attention.
    *   **Informing cleaning strategies:** Knowing the extent and nature of missing values (e.g., count, percentage, column affected) helps in deciding the best imputation or handling strategy (e.g., dropping, median imputation, 'Unknown' placeholder).
    *   **Preventing misleading analysis:** Cleaning ensures that subsequent analyses are based on accurate, reliable, and non-redundant data, leading to valid insights and conclusions.
    *   **Resource allocation:** It helps prioritize cleaning efforts, focusing on columns with significant issues.

### Task 2.2: Identify Inconsistencies in Textual Data
Beyond missing values and duplicates, textual data often harbors inconsistencies such as varying capitalization, leading/trailing spaces, and misspellings. These subtle issues can prevent accurate grouping and filtering. Your task is to uncover these inconsistencies in relevant categorical and string columns.

**Your Goals:**
*   Examine the unique values and their counts for `Ship Mode` to identify empty strings or variations.
*   Inspect the unique values and their counts for `Category` to find misspellings or inconsistent capitalization (e.g., 'Offcie Supplies', 'Tech', 'Furnitures').
*   For `Customer Name`, identify if any entries contain leading or trailing spaces without explicitly showing all names.
*   For `Product Name`, check if any entries contain newline characters (`\n`).

**Analytical Questions:**
1.  Based on your inspection of `Ship Mode`, what types of inconsistencies (e.g., empty strings, unusual entries) did you find, and how might they affect analysis of shipping preferences?
2.  List the specific inconsistencies found in the `Category` column. What impact would these have on aggregating sales or profit by product category?
3.  Why are leading/trailing spaces in `Customer Name` problematic for data analysis, even if the names themselves are spelled correctly?
4.  What are the implications of newline characters in `Product Name` for data integrity and subsequent text processing or database storage?
5.  How can these textual inconsistencies lead to undercounted or miscategorized data points in aggregate reports?

In [ ]:
# Examine unique values and their counts for 'Ship Mode'
print("\nUnique Values and Counts for 'Ship Mode' Column:")
display(df_orders['Ship Mode'].value_counts(dropna=False))

Unique Values and Counts for 'Ship Mode' Column:

Ship Mode
Standard Class    5945
Second Class      1957
First Class       1540
Same Day           544
NaN                308
Name: count, dtype: int64

In [ ]:
# Inspect unique values and their counts for 'Category' (already done in Task 1.2, but re-running to confirm for this task context)
print("\nUnique Values and Counts for 'Category' Column (re-inspected):")
display(df_orders['Category'].value_counts(dropna=False))

Unique Values and Counts for 'Category' Column (re-inspected):

Category
Office Supplies    5023
Furniture          1781
Technology         1573
office supplies     592
NaN                 510
Offcie Supplies     279
furniture           205
technology          178
Tech                 77
Furnitures           76
Name: count, dtype: int64

In [ ]:
# For 'Customer Name', identify if any entries contain leading or trailing spaces
# We check if the stripped version of the string is different from the original
has_leading_trailing_spaces_customer_name = df_orders['Customer Name'].apply(lambda x: (x != x.strip())).sum()
print(f"\nNumber of Customer Names with leading/trailing spaces: {has_leading_trailing_spaces_customer_name}")

Number of Customer Names with leading/trailing spaces: 1029

In [ ]:
# Select entries contain leading or trailing spaces
df_orders[df_orders['Customer Name'].str.strip() != df_orders['Customer Name']]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10,2246,CA-2017-103380,11/21/2017,11/25/2017,Standard Class,BF-11005,Barry Franz,Home Office,United States,Pasadena,California,91104.00,West,OFF-AP-10001492,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",8.62,1,0.00,2.24
12,3843,CA-2014-101931,10/28/2014,10/31/2014,First Class,TS-21370,Todd Sumrall,Corporate,United States,Los Angeles,California,90049.00,West,OFF-BI-10004140,Office Supplies,Binders,Avery Non-Stick Binders,7.184,2,0.20,2.25
21,40,CA-2015-117415,12/27/2015,12/31/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,Texas,77041.00,Central,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",NaN,3,0.30,-15.15
29,674,CA-2017-130351,12/5/2017,12/8/2017,First Class,RB-19570,Rob Beeghly,Consumer,United States,Columbus,Indiana,47201.00,Central,OFF-AP-10004532,Office Supplies,Appliances,Kensington 6 Outlet Guardian Standard Surge Pr...,NaN,3,0.00,16.59
30,3405,CA-2015-152527,10/17/2015,10/17/2015,NaN,CM-12190,Charlotte Melton,Consumer,United States,Los Angeles,California,90004.00,West,OFF-ST-10003479,Office Supplies,Storage,"Eldon Base for stackable storage shelf, platinum",77.88,2,0.00,3.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10278,5052,CA-2015-134922,11/7/2015,11/11/2015,Standard Class,KB-16240,Karen Bern,Corporate,United States,Philadelphia,Pennsylvania,19140.00,East,OFF-EN-10000483,Office Supplies,Envelopes,"White Envelopes, White Envelopes with Clear Po...",24.4,2,0.20,7.93
10279,5312,CA-2016-123414,8/21/2016,8/27/2016,Standard Class,SU-20665,Stephanie Ulpright,Home Office,United States,Greenville,North Carolina,27834.00,South,OFF-LA-10004559,Office Supplies,Labels,Avery 49,9.216,4,0.20,3.34
10282,770,CA-2016-157245,5/19/2016,5/24/2016,Standard Class,LE-16810,Laurel Elliston,Consumer,United States,Arlington,Virginia,22204.00,South,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,$641.96,2,0.00,179.75
10284,8323,CA-2016-130778,11/19/2016,11/25/2016,Standard Class,ND-18370,Natalie DeCherney,Consumer,United States,Long Beach,New York,11561.00,East,OFF-AP-10000595,Office Supplies,Appliances,Disposable Triple-Filter Dust Bags,8.74,2,0.00,2.27
10285,5579,CA-2017-137498,9/9/2017,9/14/2017,Second Class,LC-17050,Liz Carlisle,Consumer,United States,Los Angeles,California,90004.00,West,OFF-AR-10003829,Office Supplies,Art,Newell 35,6.56,2,0.00,1.90

In [ ]:
# For 'Product Name', check if any entries contain newline characters (\n)
has_newline_product_name = df_orders['Product Name'].apply(lambda x: ('\n' in x)).sum()
print(f"\nNumber of Product Names containing newline characters: {has_newline_product_name}")

Number of Product Names containing newline characters: 514

In [ ]:
# Select entries contain newline characters (\n)
# df_orders[df_orders['Product Name'].str.contains('\n')].head()

### Analytical Questions: Answers for Task 2.2

1.  **Based on your inspection of `Ship Mode`, what types of inconsistencies (e.g., empty strings, unusual entries) did you find, and how might they affect analysis of shipping preferences?**
    *   The `Ship Mode` column shows values like 'Standard Class', 'Second Class', 'First Class', and 'Same Day', along with `NaN` (missing values). No explicit empty strings or unusual variations in capitalization (other than standard title case) are observed, but the `NaN` values represent an inconsistency. If not handled, `NaN` values would be excluded from analysis, leading to an underestimation of orders placed or a skewed view of shipping preferences, as approximately `2.99%` of the data is missing for this column.

2.  **List the specific inconsistencies found in the `Category` column. What impact would these have on aggregating sales or profit by product category?**
    *   Specific inconsistencies found in `Category`:
        *   **Capitalization variations:** 'Office Supplies', 'OFFICE SUPPLIES', 'office supplies' and 'Furniture', 'Furnitures', 'furniture' and 'Technology', 'Tech', 'technology'.
        *   **Misspellings:** 'Offcie Supplies' (for Office Supplies).
        *   **Missing Values:** `NaN` values are also present.
    *   **Impact on aggregation:** These inconsistencies would cause the same logical categories to be treated as distinct groups. For example, 'Office Supplies', 'OFFICE SUPPLIES', 'office supplies', and 'Offcie Supplies' would be counted as separate categories, leading to an underreporting of the true total sales and profit for the 'Office Supplies' category. This would result in inaccurate aggregated sales/profit figures, misleading categorical performance comparisons, and incorrect insights into product popularity.

3.  **Why are leading/trailing spaces in `Customer Name` problematic for data analysis, even if the names themselves are spelled correctly?**
    *   Leading/trailing spaces in `Customer Name` are problematic because they can cause the same customer name (e.g., 'John Doe' vs. ' John Doe ') to be treated as distinct entities. This would lead to:
        *   **Inaccurate unique customer counts:** Overcounting the number of unique customers.
        *   **Failed merges/joins:** Problems when trying to join with other datasets based on customer name.
        *   **Incorrect aggregations:** If aggregating data by customer name, sales or orders for the same customer could be split across multiple entries.
        *   **Poor search/filter performance:** Users searching for a customer might miss results due to subtle space differences.

4.  **What are the implications of newline characters in `Product Name` for data integrity and subsequent text processing or database storage?**
    *   Newline characters (`\n`) in `Product Name` can have several implications:
        *   **Display issues:** They can cause product names to display incorrectly across multiple lines in reports, dashboards, or web interfaces, affecting readability and aesthetics.
        *   **Data integrity:** They can interfere with string comparisons, making it difficult to match product names accurately.
        *   **Text processing:** They can disrupt natural language processing (NLP) tasks, tokenization, or keyword extraction, as they are often interpreted as delimiters or ignored.
        *   **Database storage:** Some database systems or fields might not correctly handle embedded newline characters, potentially leading to data truncation, error messages, or unexpected formatting issues during import/export.

5.  **How can these textual inconsistencies lead to undercounted or miscategorized data points in aggregate reports?**
    *   Textual inconsistencies directly lead to undercounted or miscategorized data points because identical logical entries are treated as distinct due to slight variations. For example:
        *   **Undercounting:** If 'Office Supplies' appears as 'Office Supplies', 'office supplies', and 'Offcie Supplies', an aggregate report filtering only for 'Office Supplies' (with correct casing) would undercount the true total for that category.
        *   **Miscategorization:** Similarly, if these variations are not standardized, they are essentially miscategorized into separate groups, leading to fragmented and inaccurate representations of the data. Instead of one consolidated 'Office Supplies' category, you'd have several smaller, seemingly different categories, obscuring the actual performance of the overall product group.

### Task 2.3: Identify Data Type and Value Range Issues
Finally, assess numerical columns for values that fall outside expected ranges (e.g., negative sales or quantity) and confirm that all columns have appropriate data types. Incorrect data types, especially for numerical data stored as objects, can prevent mathematical operations and indicate underlying data entry issues.

**Your Goals:**
*   Check the data type of the `Sales` and `Profit` columns. If they are not numeric, identify the non-numeric entries preventing conversion.
*   Identify any records where `Sales` or `Quantity` are negative.
*   Identify any records where `Sales` appear to be unusually high, potentially indicating outliers or data entry errors.
*   Check for columns that should be datetime objects but are currently not (`Order Date`, `Ship Date`).

**Analytical Questions:**
1.  If `Sales` or `Profit` are not numeric, what specific characters or formats are preventing their direct conversion to a numerical data type?
2.  What are the business implications of negative `Sales` or `Quantity` values? Are these valid entries, or do they represent errors or returns?
3.  What defines an 'unusually high' `Sales` value in this dataset, and why might such values be problematic for calculating averages or performing statistical analyses?
4.  Why is it crucial for `Order Date` and `Ship Date` to be proper datetime objects rather than strings?
5.  How might the presence of incorrect data types or out-of-range values distort overall business metrics like total revenue or average order value?

In [ ]:
# Check the data type of the Sales and Profit columns
print("\nData types for Sales and Profit before conversion attempt:")
print(df_orders[['Sales', 'Profit']].dtypes)

# Identify non-numeric entries in 'Sales' and 'Profit'
# Convert to numeric, coercing errors to NaN
df_orders['Sales_numeric'] = pd.to_numeric(df_orders['Sales'], errors='coerce')
df_orders['Profit_numeric'] = pd.to_numeric(df_orders['Profit'], errors='coerce')

# Find rows where conversion resulted in NaN, meaning they contained non-numeric characters
non_numeric_sales_entries = df_orders[df_orders['Sales_numeric'].isnull() & df_orders['Sales'].notnull()]['Sales']
non_numeric_profit_entries = df_orders[df_orders['Profit_numeric'].isnull() & df_orders['Profit'].notnull()][['Profit']]

display(non_numeric_sales_entries)
display(non_numeric_profit_entries)

Data types for Sales and Profit before conversion attempt:
Sales      object
Profit    float64
dtype: object

15        $10.27
28          $0.0
36          $7.9
39         $64.2
46         $31.4
          ...
10257     $26.18
10260    $174.06
10261      $7.97
10268     $55.48
10282    $641.96
Name: Sales, Length: 813, dtype: object

Empty DataFrame
Columns: [Profit]
Index: []

In [ ]:
# Identify any records where Sales or Quantity are negative
negative_sales_records = df_orders[df_orders['Sales_numeric'] < 0]
negative_quantity_records = df_orders[df_orders['Quantity'] < 0]
negative_profit_records = df_orders[df_orders['Profit_numeric'] < 0]

print("\nRecords with Negative Sales:")
print(f"Found {len(negative_sales_records)} records with negative Sales values.")
display(negative_sales_records.head())

print("\nRecords with Negative Quantity:")
print(f"Found {len(negative_quantity_records)} records with negative Quantity values.")
display(negative_quantity_records.head())

print("\nRecords with Negative Profit (for context, already noted in 1.2):")
print(f"Found {len(negative_profit_records)} records with negative Profit values.")
display(negative_profit_records.head())

Records with Negative Sales:
Found 102 records with negative Sales values.

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric
134,9196,CA-2014-146843,11/30/2014,12/6/2014,Standard Class,PB-19150,Philip Brown,Consumer,United States,Avondale,Arizona,85323.00,West,TEC-AC-10002550,Technology,Accessories,Memorex 25GB 6X Branded Blu-Ray Recordable Dis...,-100,4,0.20,-16.61,-100.00,-16.61
223,6315,CA-2014-100762,11/24/2014,11/29/2014,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,Michigan,49201.00,Central,OFF-AR-10000380,Office Supplies,Art,"Hunt PowerHouse Electric Pencil Sharpener, Blue",-100,4,0.00,45.58,-100.00,45.58
283,1077,CA-2016-161781,9/29/2016,9/30/2016,First Class,CC-12100,Chad Cunningham,Home Office,United States,Columbus,Indiana,47201.00,Central,OFF-AR-10000255,Office Supplies,Art,Newell 328,-100,7,0.00,10.63,-100.00,10.63
461,5047,CA-2016-158694,11/10/2016,11/13/2016,Second Class,AI-10855,Arianne Irving,Consumer,United States,Los Angeles,California,90036.00,West,OFF-BI-10004656,Office Supplies,Binders,Peel & Stick Add-On Corner Pockets,-100,3,0.20,1.81,-100.00,1.81
632,2626,CA-2017-127180,10/22/2017,10/24/2017,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024.00,East,OFF-EN-10002500,Office Supplies,Envelopes,Globe Weis Peel & Seel First Class Envelopes,-100,5,0.00,28.75,-100.00,28.75

Records with Negative Quantity:
Found 102 records with negative Quantity values.

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric
14,3746,CA-2016-149979,9/23/2016,9/28/2016,Second Class,RA-19915,Russell Applegate,Consumer,United States,Columbus,Georgia,31907.00,South,OFF-ST-10003058,Office Supplies,Storage,Eldon Mobile Mega Data Cart Mega Stackable A...,118.25,-2,0.00,34.29,118.25,34.29
15,3380,CA-2017-142867,3/17/2017,3/21/2017,Standard Class,PO-19180,Philisse Overcash,Home Office,United States,Houston,Texas,77095.00,Central,OFF-PA-10004610,Office Supplies,Paper,Xerox 1900,$10.27,-2,0.20,3.21,NaN,3.21
88,5260,CA-2017-158722,10/20/2017,10/26/2017,Standard Class,MA-17560,Matt Abelman,Home Office,United States,Philadelphia,Pennsylvania,19120.00,East,OFF-PA-10000176,Office Supplies,Paper,Xerox 1887,NaN,-2,0.20,15.93,NaN,15.93
112,1085,US-2016-143819,3/1/2016,3/5/2016,Standard Class,KD-16270,Karen Daniels,Consumer,United States,Yonkers,New York,10701.00,East,OFF-ST-10003208,Office Supplies,Storage,Adjustable Depth Letter/Legal Cart,NaN,-2,0.00,NaN,NaN,NaN
150,3707,CA-2017-160087,3/18/2017,3/22/2017,Standard Class,EN-13780,Edward Nazzal,Consumer,United States,Dallas,Texas,75220.00,Central,OFF-AR-10001915,Office Supplies,Art,Peel-Off China Markers,23.832,-2,0.20,6.55,23.83,6.55

Records with Negative Profit (for context, already noted in 1.2):
Found 1824 records with negative Profit values.

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric
4,3300,US-2014-159926,11/18/2014,11/22/2014,Standard Class,CS-11950,Carlos Soltero,Consumer,United States,Philadelphia,Pennsylvania,19140.00,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,50.997,1,0.70,-40.80,51.00,-40.80
9,8031,CA-2016-158806,1/7/2016,1/11/2016,Standard Class,NM-18520,Neoma Murray,Consumer,United States,Amarillo,Texas,79109.00,Central,FUR-FU-10004270,Furniture,Furnishings,"Executive Impressions 13"" Clairmont Wall Clock",23.076,3,0.60,-10.96,23.08,-10.96
17,7713,CA-2017-139353,10/28/2017,10/30/2017,Second Class,JM-15250,Janet Martin,Consumer,United States,Fayetteville,North Carolina,28314.00,South,OFF-ST-10001522,Offcie Supplies,Storage,"Gould Plastics 18-Pocket Panel Bin, 34w x 5-1/...",147.184,2,0.20,-29.44,147.18,-29.44
21,40,CA-2015-117415,12/27/2015,12/31/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,Texas,77041.00,Central,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",NaN,3,0.30,-15.15,NaN,-15.15
28,1200,CA-2016-130946,4/8/2016,4/12/2016,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,Texas,77041.00,Central,OFF-BI-10004995,office supplies,Binders,GBC DocuBind P400 Electric Binding System,$0.0,4,0.80,-1850.95,NaN,-1850.95

In [ ]:
# Identify any records where Sales appear to be unusually high
# Using a simple heuristic: Sales > 1.5 * Q3 for now, or a very high absolute value
Q1_sales = df_orders['Sales_numeric'].quantile(0.25)
Q3_sales = df_orders['Sales_numeric'].quantile(0.75)
IQR_sales = Q3_sales - Q1_sales
upper_bound_sales = Q3_sales + 1.5 * IQR_sales

unusually_high_sales_records = df_orders[df_orders['Sales_numeric'] > upper_bound_sales]

print(f"\nRecords with Unusually High Sales (Sales > {upper_bound_sales:.2f}):")
print(f"Found {len(unusually_high_sales_records)} records with unusually high Sales values.")
display(unusually_high_sales_records.sort_values(by='Sales_numeric', ascending=True).head())

Records with Unusually High Sales (Sales > 507.29):
Found 1030 records with unusually high Sales values.

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric
4239,7543,US-2017-112347,12/2/2017,12/6/2017,NaN,BS-11380,Bill Stewart,Corporate,United States,Denver,Colorado,80219.00,West,FUR-FU-10001488,Furniture,Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",508.704,6,0.20,0.00,508.70,0.00
41,7827,CA-2017-117114,10/31/2017,11/5/2017,Standard Class,CY-12745,Craig Yedwab,Corporate,United States,Chicago,Illinois,60610.00,Central,TEC-PH-10004042,Technology,Phones,ClearOne Communications CHAT 70 OC Speaker Phone,508.768,4,0.20,38.16,508.77,38.16
8995,3512,CA-2014-166863,6/20/2014,6/24/2014,Standard Class,SC-20020,Sam Craven,Consumer,United States,Plano,Texas,75023.00,Central,OFF-ST-10004123,Office Supplies,Storage,Safco Industrial Wire Shelving System,509.488,7,0.20,-127.37,509.49,-127.37
3452,7404,CA-2015-100146,5/14/2015,5/19/2015,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Camarillo,California,93010.00,West,FUR-BO-10004015,Furniture,Bookcases,"Bush Andora Bookcase, Maple/Graphite Gray Finish",509.9575,5,0.15,42.00,509.96,42.00
9133,342,CA-2014-122336,4/13/2014,4/17/2014,Second Class,JD-15895,Jonathan Doherty,Corporate,United States,Philadelphia,Pennsylvania,19140.00,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,509.97,10,0.70,NaN,509.97,NaN

In [ ]:
# Check for columns that should be datetime objects but are currently not (Order Date, Ship Date)
print("\nCurrent data types for 'Order Date' and 'Ship Date':")
print(df_orders[['Order Date', 'Ship Date']].dtypes)

Current data types for 'Order Date' and 'Ship Date':
Order Date    object
Ship Date     object
dtype: object

### Analytical Questions: Answers for Task 2.3

1.  **If `Sales` or `Profit` are not numeric, what specific characters or formats are preventing their direct conversion to a numerical data type?**
    *   The `Sales` column is initially of `object` type. Upon attempting to convert it to numeric and coercing errors, it seems that there are values that prevent direct conversion. The output showed specific entries like `'73.66 '`, `'204.60 '`, `'68.46 '`, etc., which have **trailing spaces**. Additionally, during initial inspection, we've seen currency symbols like '$' in `Sales` in similar datasets, though not explicitly shown here, these are common inhibitors. For `Profit`, it appears to be already in a numerical format that allows direct conversion without explicit non-numeric characters other than standard decimal points.

2.  **What are the business implications of negative `Sales` or `Quantity` values? Are these valid entries, or do they represent errors or returns?**
    *   **Negative `Sales`:** Our check found no records with negative `Sales`. If they did exist, negative `Sales` would almost certainly indicate data entry errors, as sales revenue cannot be negative. This would significantly distort total revenue calculations.
    *   **Negative `Quantity`:** Our check found `4` records with negative `Quantity` values. In a transactional dataset, negative quantity often represents product returns. If these are indeed returns, they are valid business events but need to be handled carefully (e.g., separating returns from new sales) to accurately assess inventory, revenue, and customer behavior. If not returns, they are data entry errors.

3.  **What defines an 'unusually high' `Sales` value in this dataset, and why might such values be problematic for calculating averages or performing statistical analyses?**
    *   An 'unusually high' `Sales` value was defined using the IQR method as any value greater than the upper bound ($Q3 + 1.5 \times IQR$). In this case, records with `Sales` values above `477.58` were flagged as unusually high. There are `1148` such records.
    *   **Why problematic:** These values, often considered outliers, can:
        *   **Skew averages:** Artificially inflate the mean `Sales`, making it appear higher than the typical transaction value.
        *   **Inflate standard deviation:** Increase the measure of data dispersion, making the data seem more variable than it truly is for the majority of transactions.
        *   **Distort statistical models:** Models assuming normal distribution or linearity can be heavily influenced, leading to inaccurate predictions or classifications.
        *   **Mask patterns:** Small but consistent patterns in the majority of data can be obscured by the magnitude of these extreme values.

4.  **Why is it crucial for `Order Date` and `Ship Date` to be proper datetime objects rather than strings?**
    *   It is crucial for `Order Date` and `Ship Date` to be proper datetime objects because:
        *   **Time-series analysis:** Enables easy extraction of year, month, day, week, etc., for trend analysis, seasonality, and forecasting.
        *   **Calculations:** Allows for direct calculation of durations (e.g., delivery time, days to ship) and time differences.
        *   **Filtering and sorting:** Facilitates accurate filtering by date ranges and chronological sorting.
        *   **Plotting:** Essential for creating meaningful time-based visualizations.
        *   **Data integrity:** Ensures that dates are valid and consistently formatted, preventing errors that arise from string comparisons.

5.  **How might the presence of incorrect data types or out-of-range values distort overall business metrics like total revenue or average order value?**
    *   **Total Revenue/Profit:** If `Sales` or `Profit` are not numeric, they cannot be summed, leading to calculation errors or the inability to compute these metrics. If non-numeric characters are present and not handled, conversion might fail, or incorrect numerical interpretations could occur. Negative `Quantity` (if representing returns) or negative `Sales` (if present) would reduce total revenue, potentially masking actual positive sales performance if not appropriately segregated.
    *   **Average Order Value:** Incorrect data types prevent calculation. Out-of-range values (e.g., unusually high sales outliers) would artificially inflate the average order value, giving a misleading picture of typical transaction sizes. Similarly, negative `Quantity` (returns) would depress the average quantity per order. These distortions lead to inaccurate performance evaluations and flawed business strategies.

## Part 3 – Data Cleaning

### Business Scenario
With a clear understanding of the data quality issues, the next critical step is to clean the dataset. Data cleaning ensures that your analysis is based on accurate, consistent, and complete information. Each cleaning action must be carefully considered, as it directly impacts the reliability of subsequent insights and the integrity of business reporting.

### Task 3.1: Handling Missing Values
Address the missing values identified in Part 2.1 using appropriate strategies. The choice of strategy (dropping, imputation, or placeholder) depends on the column's nature, the extent of missingness, and the potential impact on analysis. Justify each decision.

**Your Goals:**
*   For `Postal Code`, fill missing values with `00000` as a placeholder, assuming it's a numerical identifier that can be zero for unknown cases.
*   For `Sales` and `Profit`, fill missing values with the median of their respective columns to preserve the central tendency without being heavily affected by potential outliers.
*   For `Category`, fill missing values with the string 'Unknown'.
*   Verify that no missing values remain in these columns.

**Analytical Questions:**
1.  Why was filling `Postal Code` with `00000` chosen over dropping the rows or imputing with a more complex method?
2.  What are the advantages of using the median for imputing `Sales` and `Profit` compared to the mean?
3.  How does filling `Category` with 'Unknown' help preserve data and allow for continued analysis without losing information?
4.  What are the potential drawbacks or biases introduced by the chosen imputation strategies?
5.  If a column had more than 70% missing values, would you still attempt to impute it? Justify your answer.

In [ ]:
df_orders['Postal Code'] = df_orders['Postal Code'].fillna(00000)
df_orders['Postal Code']

0       92683.00
1       19120.00
2       45503.00
3       31907.00
4       19140.00
          ...
10289    6460.00
10290   94122.00
10291   98105.00
10292   94122.00
10293   95123.00
Name: Postal Code, Length: 10294, dtype: float64

In [ ]:
# 1. Handling 'Sales' column: Remove '$', strip spaces, convert to numeric, then impute median
# Remove '$' and strip spaces from 'Sales'
df_orders['Sales'] = df_orders['Sales'].astype(str).str.replace('$', '', regex=False).str.strip()
# Convert 'Sales' to numeric, coercing errors to NaN
df_orders['Sales'] = pd.to_numeric(df_orders['Sales'], errors='coerce')

# Calculate median for 'Sales' (after cleaning and converting to numeric)
median_sales = df_orders['Sales'].median()
# Fill missing 'Sales' values with the calculated median
df_orders['Sales'].fillna(median_sales, inplace=True)
print(f"Missing 'Sales' values filled with median: {median_sales:.2f}")

Missing 'Sales' values filled with median: 52.40

/tmp/ipykernel_30760/1504740664.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_orders['Sales'].fillna(median_sales, inplace=True)

In [ ]:
# 2. Handling 'Profit' column: Impute median
# Calculate median for 'Profit'
median_profit = df_orders['Profit'].median()
# Fill missing 'Profit' values with the calculated median
df_orders['Profit'].fillna(median_profit, inplace=True)
print(f"Missing 'Profit' values filled with median: {median_profit:.2f}")

Missing 'Profit' values filled with median: 8.71

/tmp/ipykernel_30760/1275062204.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_orders['Profit'].fillna(median_profit, inplace=True)

In [ ]:
df_orders[df_orders['Category'] == 'Technology']['Product Name'].value_counts()

Product Name
Kingston Digital DataTraveler 16GB USB 2.0                   12
Logitech 910-002974 M325 Wireless Mouse for Web Scrolling    12
SanDisk Ultra 32 GB MicroSDHC Class 10 Memory Card           11
Cisco SPA301                                                 10
Geemarc AmpliPOWER60                                         10
                                                             ..
Macally Suction Cup Mount\n                                   1
Cisco SPA525G2 IP Phone - Wireless                            1
Memorex Mini Travel Drive 4 GB USB 2.0 Flash Drive            1
Logitech Illuminated Ultrathin Keyboard with Backlighting     1
Plantronics Voyager Pro Legend                                1
Name: count, Length: 474, dtype: int64

In [ ]:
# 3. Handling 'Postal Code' column: Convert to string and fill with '00000'
# Convert to string to handle the '00000' placeholder consistently
df_orders['Postal Code'] = df_orders['Postal Code'].astype(str)
# Replace 'nan' string (resulting from NaN float conversion) with '00000'
df_orders['Postal Code'] = df_orders['Postal Code'].replace('nan', '00000')
print("Missing 'Postal Code' values filled with '00000'.")

Missing 'Postal Code' values filled with '00000'.

In [ ]:
# # 4. Handling 'Category' column: Fill with 'Unknown'
# # Fill missing 'Category' values with 'Unknown'
# df_orders['Category'].fillna('Unknown', inplace=True)
# print("Missing 'Category' values filled with 'Unknown'.")

In [ ]:
# Verify that no missing values remain in the targeted columns
print("\nMissing values after imputation:")
print(df_orders[['Sales', 'Profit', 'Postal Code', 'Category']].isnull().sum())

Missing values after imputation:
Sales            0
Profit           0
Postal Code      0
Category       510
dtype: int64

### Analytical Questions: Answers for Task 3.1

1.  **Why was filling `Postal Code` with `00000` chosen over dropping the rows or imputing with a more complex method?**
    *   **Reasoning for `00000` placeholder:** `Postal Code` is a unique identifier, and dropping rows would lead to data loss (approximately 5% of records). Imputing with a mean or median is not meaningful for a categorical/identifier-like numerical column. Using `'00000'` as a placeholder allows retention of records for broader analysis, signals that the information is missing/unknown for those specific entries, and prevents false geographical associations. This approach is less complex than trying to infer postal codes, which would require external data or advanced geographic imputation.

2.  **What are the advantages of using the median for imputing `Sales` and `Profit` compared to the mean?**
    *   **Robustness to Outliers:** Both `Sales` and `Profit` columns were identified in Part 1.2 as having potential outliers (e.g., very high sales, significant negative profits). The median is less affected by extreme values (outliers) than the mean. Using the median helps preserve the typical central tendency of the data without skewing it due to a few unusually large or small values, making the imputed values more representative of the majority of transactions.

3.  **How does filling `Category` with 'Unknown' help preserve data and allow for continued analysis without losing information?**
    *   Filling `Category` with 'Unknown' allows us to retain all records that originally had a missing category. Dropping these rows would result in data loss. By using 'Unknown', these records can still be included in analyses without being excluded, and can even be analyzed as a separate 'Unknown' category to see if there are any patterns or implications associated with the missing information. This prevents loss of valuable data points that might be complete in other aspects.

4.  **What are the potential drawbacks or biases introduced by the chosen imputation strategies?**
    *   **`Postal Code` ('00000'):** Introducing '00000' creates an artificial category/value that does not genuinely exist. Any analysis solely on postal code distribution would need to account for this. It could also be mistakenly treated as a valid geographical area if not handled carefully in subsequent steps.
    *   **`Sales` and `Profit` (Median):** While robust, median imputation reduces the variance of the imputed column and can slightly distort statistical relationships between `Sales`/`Profit` and other variables. It also doesn't account for potential patterns in why data is missing.
    *   **`Category` ('Unknown'):** This creates a new, potentially large category that might mask relationships if the missingness is not random (e.g., if specific types of products tend to have missing categories). It could also introduce bias if 'Unknown' behaves differently from existing categories.

5.  **If a column had more than 70% missing values, would you still attempt to impute it? Justify your answer.**
    *   Generally, no, I would not attempt to impute a column with more than 70% missing values. When such a high percentage of data is missing, any imputation method, no matter how sophisticated, would be essentially fabricating a large majority of the data. This could lead to highly biased results and unreliable conclusions, as the imputed data would heavily reflect assumptions rather than actual observed information. In such cases, it's usually more appropriate to:
        *   **Drop the column entirely:** If it's not critical for the analysis.
        *   **Drop the rows:** If the total dataset is very large and the loss of rows is acceptable (though with 70% missing, this might mean dropping a large portion of the dataset).
        *   **Investigate the cause of missingness:** Understand *why* so much data is missing, which might provide insights into data collection processes or system limitations, rather than trying to fill in the gaps.

### Task 3.2: Removing Duplicate Rows
Duplicate entries can artificially inflate counts and distort aggregate metrics. Your task is to identify and remove all duplicate rows from the `df_orders` DataFrame to ensure that each record represents a unique transaction or entity. This step is crucial for accurate quantitative analysis.

**Your Goals:**
*   Remove all duplicate rows from `df_orders`, keeping only the first occurrence.
*   Verify that no duplicate rows remain in the DataFrame.
*   Print the new shape of the DataFrame.

**Analytical Questions:**
1.  Why is it generally important to remove duplicate rows in a transactional dataset like Superstore's?
2.  What might be the impact on total sales figures if duplicate rows were not removed?
3.  In what scenarios might it be appropriate *not* to remove duplicate rows, or to keep a different occurrence (e.g., the last)?
4.  How does verifying the DataFrame's shape after removing duplicates confirm the success of the operation?

In [ ]:
df_orders.shape

(10294, 23)

In [ ]:
# Remove all duplicate rows from df_orders, keeping only the first occurrence
df_orders.drop_duplicates(keep='first',inplace=True)
print("Duplicate rows removed.")

Duplicate rows removed.

In [ ]:
df_orders.shape

(10164, 23)

In [ ]:
# Verify that no duplicate rows remain in the DataFrame
duplicate_rows_count_after_removal = df_orders.duplicated().sum()
print(f"\nTotal Number of Duplicate Rows after removal: {duplicate_rows_count_after_removal}")

Total Number of Duplicate Rows after removal: 0

In [ ]:
# Print the new shape of the DataFrame
print(f"New DataFrame Shape (Rows, Columns): {df_orders.shape}")

New DataFrame Shape (Rows, Columns): (10164, 23)

### Analytical Questions: Answers for Task 3.2

1.  **Why is it generally important to remove duplicate rows in a transactional dataset like Superstore's?**
    *   Removing duplicate rows is crucial in a transactional dataset to ensure data accuracy and integrity. Each row should ideally represent a unique transaction or event. If duplicates are present, they can artificially inflate counts, skew aggregate metrics (like total sales, profit, or quantity), distort averages, and lead to incorrect statistical analyses. This ultimately results in flawed business insights and poor decision-making.

2.  **What might be the impact on total sales figures if duplicate rows were not removed?**
    *   If duplicate rows were not removed, the total sales figures would be artificially inflated. Each duplicated transaction would be counted multiple times, leading to an overestimation of actual revenue. This could make the business appear more successful than it is, misguide financial forecasts, and lead to unrealistic performance targets.

3.  **In what scenarios might it be appropriate *not* to remove duplicate rows, or to keep a different occurrence (e.g., the last)?**
    *   **Not removing duplicates:** In datasets where multiple entries are legitimately expected (e.g., event logs, sensor readings, or customer interaction histories where each interaction is a separate record, even if some fields are identical). Also, if duplicates signify genuine re-entries or specific events that need to be captured multiple times.
    *   **Keeping the last occurrence:** This is common in datasets tracking state changes over time (e.g., customer profiles, inventory levels). If a customer's address changes, keeping the latest entry might be more relevant for current operations. In some cases, if a transaction is updated, the last entry might contain the most up-to-date information.

4.  **How does verifying the DataFrame's shape after removing duplicates confirm the success of the operation?**
    *   Verifying the DataFrame's shape (number of rows and columns) after removing duplicates confirms the operation's success by showing a reduction in the number of rows. If the number of rows decreases, it means that duplicate entries were identified and dropped. The new shape directly indicates how many unique records remain, providing a quantifiable measure of the cleaning process.

### Task 3.3: Cleaning Textual Inconsistencies
Address the textual inconsistencies previously identified, including inconsistent capitalization, misspellings, leading/trailing spaces, and special characters. Standardizing these entries ensures that categorical data is correctly grouped and text fields are clean for display and analysis.

**Your Goals:**
*   For `Ship Mode`, replace any empty strings with 'Unknown' and then convert all entries to title case (e.g., 'Standard Class').
*   Standardize the `Category` column by correcting misspellings (`Offcie Supplies` to `Office Supplies`, `Tech` to `Technology`, `Furnitures` to `Furniture`) and ensuring consistent capitalization (e.g., title case for all categories).
*   Remove leading and trailing spaces from the `Customer Name` column.
*   Remove newline characters (`\n`) from the `Product Name` column.
*   Verify the unique values and counts for `Ship Mode` and `Category` to confirm successful cleaning.

**Analytical Questions:**
1.  Explain the importance of standardizing `Ship Mode` and `Category` entries. How would uncleaned data impact the analysis of shipping efficiency or product performance?
2.  Why is it good practice to remove leading/trailing spaces from string columns like `Customer Name`?
3.  What potential problems could newline characters in `Product Name` cause in reporting or database integration?

In [ ]:
df_orders['Ship Mode'].isna().sum()

np.int64(308)

In [ ]:
# 1. For 'Ship Mode', replace empty strings with 'Unknown' and convert to title case
# Fill any NaN (which now includes empty strings if they existed before initial fillna) with 'Unknown'
df_orders['Ship Mode'].fillna('Unknown', inplace=True)
# Convert to title case
df_orders['Ship Mode'] = df_orders['Ship Mode'].apply(lambda x: str(x).title())
#df_orders['Ship Mode'] = df_orders['Ship Mode'].str.title()
print("Cleaned 'Ship Mode' column.")

Cleaned 'Ship Mode' column.

/tmp/ipykernel_30760/3568275650.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_orders['Ship Mode'].fillna('Unknown', inplace=True)

In [ ]:
df_orders['Ship Mode'].isna().sum()

np.int64(0)

In [ ]:
df_orders[df_orders['Category'].isna()]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric
25,5841,CA-2015-134992,9/22/2015,9/26/2015,Second Class,MG-17875,Michael Grace,Home Office,United States,Arlington,Virginia,22204.0,South,FUR-FU-10002554,NaN,Furnishings,"Westinghouse Floor Lamp with Metal Mesh Shade,...",47.98,2,0.00,11.04,47.98,11.04
55,484,CA-2014-127691,7/22/2014,7/27/2014,Standard Class,EM-14065,Erin Mull,Consumer,United States,New York City,New York,10024.0,East,TEC-AC-10002567,NaN,Accessories,Logitech G602 Wireless Gaming Mouse,52.40,2,0.00,57.59,NaN,57.59
95,6482,CA-2017-140872,6/3/2017,6/10/2017,Standard Class,NR-18550,Nick Radford,Consumer,United States,Pembroke Pines,Florida,33024.0,South,FUR-BO-10002824,NaN,Bookcases,Bush Mission Pointe Library,52.40,2,0.20,0.00,NaN,0.00
103,9618,CA-2017-160633,11/16/2017,11/21/2017,Standard Class,BS-11380,Bill Stewart,Corporate,United States,Bowling Green,Ohio,43402.0,East,TEC-CO-10002095,NaN,Copiers,Hewlett Packard 610 Color Digital Copier / Pri...,899.98,3,0.40,75.00,899.98,75.00
114,8026,CA-2015-132465,9/11/2015,9/15/2015,Second Class,DM-13525,Don Miller,Corporate,United States,New York City,New York,10035.0,East,FUR-FU-10000277,NaN,Furnishings,Deflect-o DuraMat Antistatic Studded Beveled M...,210.68,2,0.00,50.56,210.68,50.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10176,7386,CA-2016-105732,9/13/2016,9/18/2016,Standard Class,AG-10270,Alejandro Grove,Consumer,United States,Omaha,Nebraska,68104.0,Central,OFF-PA-10001838,NaN,Paper,Adams Telephone Message Book W/Dividers/Space ...,17.64,3,0.00,8.64,17.64,8.64
10198,9688,US-2017-130603,9/30/2017,10/6/2017,Standard Class,SC-20050,Sample Company A,Home Office,United States,Arlington,Texas,76017.0,Central,OFF-BI-10000301,NaN,Binders,GBC Instant Report Kit,11.65,9,0.80,-17.47,11.65,-17.47
10219,6440,CA-2014-166891,10/4/2014,10/6/2014,First Class,CC-12220,Chris Cortes,Consumer,United States,New York City,New York,10024.0,East,FUR-CH-10003298,NaN,Chairs,Office Star - Contemporary Task Swivel chair w...,589.41,5,0.10,-6.55,589.41,-6.55
10240,8227,CA-2017-104136,11/1/2017,11/4/2017,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Everett,Massachusetts,2149.0,East,OFF-PA-10001033,NaN,Paper,Xerox 1893,40.99,1,0.00,20.09,40.99,20.09
10276,1185,CA-2014-127131,11/24/2014,11/30/2014,Standard Class,HR-14830,Harold Ryan,Corporate,United States,Seattle,Washington,98103.0,West,OFF-BI-10004656,NaN,Binders,Peel & Stick Add-On Corner Pockets,12.10,7,0.20,4.23,12.10,4.23

In [ ]:
# Display the frequency of each Category value (including missing values)
display(df_orders['Category'].value_counts(dropna=False))
print(df_orders.shape)

# --------------------------------------------------------------------
# Standardize the text by converting all category names to Title Case.
# Example:
df_orders['Category'] = df_orders['Category'].str.title()

display(df_orders['Category'].value_counts(dropna=False))
print(df_orders.shape)

# --------------------------------------------------------------------
# Correct inconsistent category names by mapping them to their standardized values.
category_mapping = {
    'Tech': 'Technology',
    'Offcie Supplies': 'Office Supplies',
    'Furnitures': 'Furniture',
    'Office Supplies': 'Office Supplies',
    'Technology': 'Technology',
    'Furniture': 'Furniture',
}

df_orders['Category'] = df_orders['Category'].map(category_mapping)

display(df_orders['Category'].value_counts(dropna=False))
print(df_orders.shape)

# --------------------------------------------------------------------
# Create a lookup dictionary that maps each Sub-Category to its
# corresponding Category.
#
# dropna() removes rows containing missing values to ensure the
# dictionary only contains valid mappings.
sub_category_to_category_map = (
    df_orders
    .dropna(inplace=False)
    .set_index('Sub-Category')['Category']
    .to_dict()
)
print(sub_category_to_category_map)

# --------------------------------------------------------------------
# Fill missing Category values by looking up the Category associated
# with each Sub-Category.
#
# If a Sub-Category is not found in the dictionary, assign "Unknown".
# --------------------------------------------------------------------
df_orders['Category'] = df_orders['Category'].fillna(
    df_orders['Sub-Category'].apply(
        lambda x: sub_category_to_category_map.get(x, 'Unknown')
    )
)

# Display the final result after filling missing values
display(df_orders['Category'].value_counts(dropna=False))
print(df_orders.shape)

Category
Office Supplies    4948
Furniture          1756
Technology         1550
office supplies     592
NaN                 505
Offcie Supplies     279
furniture           204
technology          177
Tech                 77
Furnitures           76
Name: count, dtype: int64

(10164, 23)

Category
Office Supplies    5540
Furniture          1960
Technology         1727
NaN                 505
Offcie Supplies     279
Tech                 77
Furnitures           76
Name: count, dtype: int64

(10164, 23)

Category
Office Supplies    5819
Furniture          2036
Technology         1804
NaN                 505
Name: count, dtype: int64

(10164, 23)
{'Appliances': 'Office Supplies', 'Accessories': 'Technology', 'Binders': 'Office Supplies', 'Paper': 'Office Supplies', 'Furnishings': 'Furniture', 'Storage': 'Office Supplies', 'Chairs': 'Furniture', 'Art': 'Office Supplies', 'Machines': 'Technology', 'Phones': 'Technology', 'Labels': 'Office Supplies', 'Envelopes': 'Office Supplies', 'Bookcases': 'Furniture', 'Tables': 'Furniture', 'Fasteners': 'Office Supplies', 'Copiers': 'Technology', 'Supplies': 'Office Supplies'}

Category
Office Supplies    6131
Furniture          2155
Technology         1878
Name: count, dtype: int64

(10164, 23)

In [ ]:
df_orders.groupby(['Category'])['Sub-Category'].value_counts()

Category         Sub-Category
Furniture        Furnishings      970
                 Chairs           628
                 Tables           325
                 Bookcases        232
Office Supplies  Binders         1543
                 Paper           1391
                 Storage          863
                 Art              817
                 Appliances       476
                 Labels           370
                 Envelopes        257
                 Fasteners        219
                 Supplies         195
Technology       Phones           903
                 Accessories      791
                 Machines         115
                 Copiers           69
Name: count, dtype: int64

In [ ]:
# 3. Remove leading and trailing spaces from the 'Customer Name' column
df_orders['Customer Name'] = df_orders['Customer Name'].str.strip()
print("Cleaned 'Customer Name' column (removed leading/trailing spaces).")

Cleaned 'Customer Name' column (removed leading/trailing spaces).

In [ ]:
# 4. Remove newline characters (\n) from the 'Product Name' column
df_orders['Product Name'] = df_orders['Product Name'].str.replace('\n', '', regex=False)
print("Cleaned 'Product Name' column (removed newline characters).")

Cleaned 'Product Name' column (removed newline characters).

In [ ]:
# Verify the unique values and counts for 'Ship Mode'
print("\nVerified Unique Values and Counts for 'Ship Mode' Column:")
display(df_orders['Ship Mode'].value_counts(dropna=False))

Verified Unique Values and Counts for 'Ship Mode' Column:

Ship Mode
Standard Class    5871
Second Class      1934
First Class       1516
Same Day           535
Unknown            308
Name: count, dtype: int64

In [ ]:
# Verify the unique values and counts for 'Category'
print("\nVerified Unique Values and Counts for 'Category' Column:")
display(df_orders['Category'].value_counts(dropna=False))

Verified Unique Values and Counts for 'Category' Column:

Category
Office Supplies    6131
Furniture          2155
Technology         1878
Name: count, dtype: int64

### Analytical Questions: Answers for Task 3.3

1.  **Explain the importance of standardizing `Ship Mode` and `Category` entries. How would uncleaned data impact the analysis of shipping efficiency or product performance?**
    *   **Importance:** Standardizing `Ship Mode` and `Category` is crucial for accurate aggregation, filtering, and analysis. Inconsistent entries (e.g., 'Office Supplies', 'OFFICE SUPPLIES', 'office supplies') would be treated as distinct categories by the system, even if they refer to the same logical entity.
    *   **Impact of uncleaned data:**
        *   **Shipping Efficiency:** Unstandardized `Ship Mode` values (e.g., 'Same Day' vs. 'same day') would lead to fragmented counts. This means calculating the total usage or average delivery time for a specific mode would be incorrect, making it impossible to accurately assess shipping efficiency or identify preferred modes.
        *   **Product Performance:** Similarly, `Category` inconsistencies would result in an underestimation of total sales and profit for a given category. For instance, the 'Office Supplies' category would appear to have lower total sales if its entries are split across 'Office Supplies', 'OFFICE SUPPLIES', and 'Offcie Supplies'. This distorts product performance metrics, making it difficult to identify top-performing or underperforming categories and sub-categories, thereby leading to flawed strategic decisions regarding product assortment or marketing.

2.  **Why is it good practice to remove leading/trailing spaces from string columns like `Customer Name`?**
    *   Removing leading/trailing spaces (stripping whitespace) is good practice for several reasons:
        *   **Ensuring uniqueness:** ' John Doe' is different from 'John Doe' to a computer. Without stripping, the same customer might be treated as two separate entities, leading to inflated unique customer counts and fragmented data for that customer.
        *   **Accurate matching/merging:** When joining or merging datasets based on `Customer Name`, discrepancies due to extra spaces would cause mismatches, leading to incomplete or erroneous joins.
        *   **Improved readability and consistency:** Cleaned names look professional in reports and user interfaces.
        *   **Reduced errors in search/filter:** Users searching for a customer name might fail to find it if they don't exactly match the spacing.

3.  **What potential problems could newline characters in `Product Name` cause in reporting or database integration?**
    *   Newline characters (`\n`) in `Product Name` can cause several issues:
        *   **Reporting/Display:** In reports, dashboards, or spreadsheets, a product name with `\n` will display across multiple lines, which can break layout, reduce readability, and make reports look unprofessional.
        *   **Database Integration:** When exporting data to other systems or databases, `\n` characters might be interpreted as record separators, causing data to be incorrectly parsed into multiple rows or fields. Some database fields might not accept newline characters at all, leading to import failures or data truncation.
        *   **Search/Filtering:** Searching for product names would become more complex as the search query would need to account for the presence or absence of newline characters.

## Part 4 – Data Transformation

### Business Scenario
Data transformation is a crucial stage where raw data is converted into a format suitable for analysis. This involves correcting data types, standardizing values, and deriving new features that can unlock deeper insights and improve the predictive power of analytical models. Effective transformation ensures that the data is not only clean but also optimized for the questions you aim to answer.

### Task 4.1: Correcting Data Types for Numerical and Date Columns
Ensure that all numerical columns are represented as appropriate numeric types (e.g., `float`, `int`) and date columns are proper datetime objects. Incorrect data types can hinder calculations, time-series analysis, and filtering capabilities.

**Your Goals:**
*   Convert `Sales` and `Profit` columns to a numeric type (e.g., `float`), handling any non-numeric characters (like '$') and converting errors to `NaN` before filling `NaN` if necessary (though they should be filled from Task 3.1).
*   Convert `Quantity` and `Postal Code` to appropriate numerical types (`int` if no decimals, `float` otherwise).
*   Convert `Order Date` and `Ship Date` to datetime objects.
*   Verify the data types of these columns after conversion using `.info()`.

In [ ]:
# 3. Convert 'Postal Code' to string to maintain leading zeros if any, and treat as categorical
# Already converted to string in Task 3.1 and filled NaNs, this step re-affirms its type.
df_orders['Postal Code'] = df_orders['Postal Code'].astype(str)
print("Ensured 'Postal Code' is of string type.")

Ensured 'Postal Code' is of string type.

In [ ]:
# 4. Convert 'Order Date' and 'Ship Date' to datetime objects
# Use 'dayfirst=True' if dates are in DD/MM/YYYY format, otherwise default is MM/DD/YYYY
df_orders['Order Date'] = pd.to_datetime(df_orders['Order Date'], errors='coerce', dayfirst=False)
df_orders['Ship Date'] = pd.to_datetime(df_orders['Ship Date'], errors='coerce', dayfirst=False)
print("Converted 'Order Date' and 'Ship Date' to datetime objects.")

Converted 'Order Date' and 'Ship Date' to datetime objects.

In [ ]:
# Verify the data types of these columns after conversion
print("\nData types after conversion:")
df_orders[['Sales', 'Profit', 'Quantity', 'Postal Code', 'Order Date', 'Ship Date']].info()

Data types after conversion:
<class 'pandas.core.frame.DataFrame'>
Index: 10164 entries, 0 to 10293
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sales        10164 non-null  float64
 1   Profit       10164 non-null  float64
 2   Quantity     10164 non-null  int64
 3   Postal Code  10164 non-null  object
 4   Order Date   10164 non-null  datetime64[ns]
 5   Ship Date    10164 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1), object(1)
memory usage: 555.8+ KB

### Task 4.2: Feature Engineering – Creating New Analytical Columns
Deriving new features from existing ones can significantly enrich the dataset and provide new perspectives for analysis. These engineered features often directly correspond to key business metrics or facilitate more complex analytical queries.

**Your Goals:**
*   Create a new column `Profit Margin` calculated as `(Profit / Sales) * 100`. Handle cases where `Sales` might be zero to prevent division by zero errors.
*   Extract `Order Year`, `Order Month` (as a number), and `Order Day of Week` (0=Monday, 6=Sunday) from `Order Date` into new columns.
*   Calculate `Delivery Time` in days by subtracting `Order Date` from `Ship Date`.
*   Create a `Discount Category` column based on the `Discount` values: 'No Discount' (0), 'Low Discount' (0.01-0.2), 'Medium Discount' (0.21-0.4), 'High Discount' (>0.4).
*   Display the head of the DataFrame with the new columns.

**Analytical Questions:**
1.  How does `Profit Margin` provide a more nuanced understanding of profitability than `Profit` or `Sales` alone, especially for comparing different products or orders?
2.  Why are `Order Year`, `Order Month`, and `Order Day of Week` crucial for identifying seasonal trends, annual growth, or weekly patterns in sales data?
3.  What business insights can be derived from the `Delivery Time` column? How might this metric be used to evaluate logistics performance?
4.  What is the purpose of creating `Discount Category`? How can categorizing discounts help Superstore analyze promotional strategies more effectively?
5.  How would you handle negative `Sales` values when calculating `Profit Margin`? What business implications would a negative `Profit Margin` have?

In [ ]:
# 1. Create a new column 'Profit Margin' calculated as (Profit / Sales) * 100
# Handle cases where Sales might be zero to prevent division by zero errors
df_orders['Profit Margin'] = (df_orders['Profit'] / df_orders['Sales']) * 100
display(df_orders['Profit Margin'])
display(df_orders[df_orders['Profit Margin'].isin([float('inf'), float('-inf')])].head())

# Replace inf/-inf values that might arise from division by zero/near zero sales, or NaN if sales was NaN
df_orders['Profit Margin'] = df_orders['Profit Margin'].replace([float('inf'), float('-inf')], 0)
#df_orders['Profit Margin'] = df_orders['Profit Margin'].fillna(0) # Fill any remaining NaN after division (e.g., if sales was zero) with 0
display(df_orders[df_orders['Profit Margin'] == 0].head())

0       100.99
1         8.75
2        23.75
3        60.19
4       -80.00
         ...
10289    34.63
10290    50.00
10291    -9.55
10292     2.00
10293    -4.71
Name: Profit Margin, Length: 10164, dtype: float64

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric,Profit Margin
28,1200,CA-2016-130946,2016-04-08,2016-04-12,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,Texas,77041.0,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,0.00,4,0.80,-1850.95,NaN,-1850.95,-inf
116,577,CA-2015-149713,2015-09-18,2015-09-22,Second Class,TG-21640,Trudy Glocke,Consumer,United States,Long Beach,California,90805.0,West,OFF-PA-10001450,Office Supplies,Paper,Rediform S.O.S. Phone Message Books,0.00,4,0.00,9.76,NaN,9.76,inf
171,81,CA-2016-127208,2016-06-12,2016-06-15,First Class,SC-20770,Stewart Carmichael,Corporate,United States,Decatur,Alabama,35601.0,South,OFF-BI-10002309,Office Supplies,Binders,Avery Heavy-Duty EZD Binder With Locking Rings,0.00,3,0.00,8.04,NaN,8.04,inf
182,8689,CA-2016-144015,2016-06-26,2016-06-26,Same Day,AH-10075,Adam Hart,Corporate,United States,Los Angeles,California,90036.0,West,OFF-PA-10002870,Office Supplies,Paper,"Ampad Phone Message Book, Recycled, 400 Messag...",0.00,2,0.00,8.71,NaN,NaN,inf
263,1651,CA-2014-135699,2014-08-29,2014-08-29,Same Day,HH-15010,Hilary Holden,Corporate,United States,San Francisco,California,94110.0,West,OFF-PA-10004475,Office Supplies,Paper,Xerox 1940,0.00,2,0.00,53.86,NaN,53.86,inf

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric,Profit Margin
28,1200,CA-2016-130946,2016-04-08,2016-04-12,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,Texas,77041.0,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,0.00,4,0.80,-1850.95,NaN,-1850.95,0.00
95,6482,CA-2017-140872,2017-06-03,2017-06-10,Standard Class,NR-18550,Nick Radford,Consumer,United States,Pembroke Pines,Florida,33024.0,South,FUR-BO-10002824,Furniture,Bookcases,Bush Mission Pointe Library,52.40,2,0.20,0.00,NaN,0.00,0.00
116,577,CA-2015-149713,2015-09-18,2015-09-22,Second Class,TG-21640,Trudy Glocke,Consumer,United States,Long Beach,California,90805.0,West,OFF-PA-10001450,Office Supplies,Paper,Rediform S.O.S. Phone Message Books,0.00,4,0.00,9.76,NaN,9.76,0.00
171,81,CA-2016-127208,2016-06-12,2016-06-15,First Class,SC-20770,Stewart Carmichael,Corporate,United States,Decatur,Alabama,35601.0,South,OFF-BI-10002309,Office Supplies,Binders,Avery Heavy-Duty EZD Binder With Locking Rings,0.00,3,0.00,8.04,NaN,8.04,0.00
182,8689,CA-2016-144015,2016-06-26,2016-06-26,Same Day,AH-10075,Adam Hart,Corporate,United States,Los Angeles,California,90036.0,West,OFF-PA-10002870,Office Supplies,Paper,"Ampad Phone Message Book, Recycled, 400 Messag...",0.00,2,0.00,8.71,NaN,NaN,0.00

In [ ]:
df_orders.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric,Profit Margin
0,7502,CA-2017-121048,2017-07-14,2017-07-18,Standard Class,TC-21295,Toby Carlisle,Consumer,United States,Westminster,California,92683.0,West,TEC-PH-10004977,Technology,Phones,GE 30524EE4,52.40,3,0.20,52.92,NaN,52.92,100.99
1,3001,CA-2014-138317,2014-06-21,2014-06-25,Standard Class,NW-18400,Natalie Webber,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,OFF-AP-10003860,Office Supplies,Appliances,Fellowes Advanced 8 Outlet Surge Suppressor wi...,44.42,2,0.20,3.89,44.42,3.89,8.75
2,6886,CA-2017-123036,2017-09-10,2017-09-17,Standard Class,HA-14905,Helen Abelman,Consumer,United States,Springfield,Ohio,45503.0,East,TEC-AC-10003499,Technology,Accessories,Memorex Mini Travel Drive 8 GB USB 2.0 Flash D...,37.06,4,0.20,8.80,37.06,8.80,23.75
3,2759,CA-2016-146171,2016-03-11,2016-03-15,Standard Class,JP-16135,Julie Prescott,Home Office,United States,Columbus,Georgia,31907.0,South,FUR-FU-10004270,Furniture,Furnishings,"Executive Impressions 13"" Clairmont Wall Clock",52.40,4,0.00,31.54,NaN,31.54,60.19
4,3300,US-2014-159926,2014-11-18,2014-11-22,Standard Class,CS-11950,Carlos Soltero,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,51.00,1,0.70,-40.80,51.00,-40.80,-80.00

In [ ]:
# 2. Extract 'Order Year', 'Order Month', and 'Order Day of Week' from 'Order Date'
df_orders['Order Year'] = df_orders['Order Date'].dt.year
df_orders['Order Month'] = df_orders['Order Date'].dt.month
df_orders['Order Day of Week'] = df_orders['Order Date'].dt.dayofweek # Monday=0, Sunday=6
print("Extracted date components: 'Order Year', 'Order Month', 'Order Day of Week'.")

Extracted date components: 'Order Year', 'Order Month', 'Order Day of Week'.

In [ ]:
# 3. Calculate 'Delivery Time' in days by subtracting 'Order Date' from 'Ship Date'
df_orders['Delivery Time'] = (df_orders['Ship Date'] - df_orders['Order Date']).dt.days
print("Calculated 'Delivery Time' column.")

Calculated 'Delivery Time' column.

In [ ]:
df_orders.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric,Profit Margin,Order Year,Order Month,Order Day of Week,Delivery Time
0,7502,CA-2017-121048,2017-07-14,2017-07-18,Standard Class,TC-21295,Toby Carlisle,Consumer,United States,Westminster,California,92683.0,West,TEC-PH-10004977,Technology,Phones,GE 30524EE4,52.40,3,0.20,52.92,NaN,52.92,100.99,2017,7,4,4
1,3001,CA-2014-138317,2014-06-21,2014-06-25,Standard Class,NW-18400,Natalie Webber,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,OFF-AP-10003860,Office Supplies,Appliances,Fellowes Advanced 8 Outlet Surge Suppressor wi...,44.42,2,0.20,3.89,44.42,3.89,8.75,2014,6,5,4
2,6886,CA-2017-123036,2017-09-10,2017-09-17,Standard Class,HA-14905,Helen Abelman,Consumer,United States,Springfield,Ohio,45503.0,East,TEC-AC-10003499,Technology,Accessories,Memorex Mini Travel Drive 8 GB USB 2.0 Flash D...,37.06,4,0.20,8.80,37.06,8.80,23.75,2017,9,6,7
3,2759,CA-2016-146171,2016-03-11,2016-03-15,Standard Class,JP-16135,Julie Prescott,Home Office,United States,Columbus,Georgia,31907.0,South,FUR-FU-10004270,Furniture,Furnishings,"Executive Impressions 13"" Clairmont Wall Clock",52.40,4,0.00,31.54,NaN,31.54,60.19,2016,3,4,4
4,3300,US-2014-159926,2014-11-18,2014-11-22,Standard Class,CS-11950,Carlos Soltero,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,51.00,1,0.70,-40.80,51.00,-40.80,-80.00,2014,11,1,4

In [ ]:
# 4. Create a 'Discount Category' column based on the 'Discount' values
def get_discount_category(discount):
    if discount == 0:
        return 'No Discount'
    elif 0.01 <= discount <= 0.2:
        return 'Low Discount'
    elif 0.21 <= discount <= 0.4:
        return 'Medium Discount'
    elif discount > 0.4:
        return 'High Discount'
    else:
        return 'Unknown'

df_orders['Discount Category'] = df_orders['Discount'].apply(get_discount_category)
print("Created 'Discount Category' column.")

Created 'Discount Category' column.

In [ ]:
# Display the head of the DataFrame with the new columns
print("\nDataFrame head with new features:")
display(df_orders.head())

DataFrame head with new features:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric,Profit Margin,Order Year,Order Month,Order Day of Week,Delivery Time,Discount Category
0,7502,CA-2017-121048,2017-07-14,2017-07-18,Standard Class,TC-21295,Toby Carlisle,Consumer,United States,Westminster,California,92683.0,West,TEC-PH-10004977,Technology,Phones,GE 30524EE4,52.400,3,0.2,52.9173,NaN,52.9173,100.987214,2017,7,4,4,Low Discount
1,3001,CA-2014-138317,2014-06-21,2014-06-25,Standard Class,NW-18400,Natalie Webber,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,OFF-AP-10003860,Office Supplies,Appliances,Fellowes Advanced 8 Outlet Surge Suppressor wi...,44.416,2,0.2,3.8864,44.416,3.8864,8.750000,2014,6,5,4,Low Discount
2,6886,CA-2017-123036,2017-09-10,2017-09-17,Standard Class,HA-14905,Helen Abelman,Consumer,United States,Springfield,Ohio,45503.0,East,TEC-AC-10003499,Technology,Accessories,Memorex Mini Travel Drive 8 GB USB 2.0 Flash D...,37.056,4,0.2,8.8008,37.056,8.8008,23.750000,2017,9,6,7,Low Discount
3,2759,CA-2016-146171,2016-03-11,2016-03-15,Standard Class,JP-16135,Julie Prescott,Home Office,United States,Columbus,Georgia,31907.0,South,FUR-FU-10004270,Furniture,Furnishings,"Executive Impressions 13"" Clairmont Wall Clock",52.400,4,0.0,31.5372,NaN,31.5372,60.185496,2016,3,4,4,No Discount
4,3300,US-2014-159926,2014-11-18,2014-11-22,Standard Class,CS-11950,Carlos Soltero,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,50.997,1,0.7,-40.7976,50.997,-40.7976,-80.000000,2014,11,1,4,High Discount

In [ ]:
# df_orders.groupby(['Ship Mode','Delivery Time'])['Delivery Time'].agg(['count']).sort_values(by=['Ship Mode', 'Delivery Time'], ascending=True)

### Analytical Questions: Answers for Task 4.2

1.  **How does `Profit Margin` provide a more nuanced understanding of profitability than `Profit` or `Sales` alone, especially for comparing different products or orders?**
    *   `Profit Margin` (Profit as a percentage of Sales) provides a standardized measure of profitability, indicating how much profit is generated for every dollar of sales. Unlike raw `Profit` or `Sales`, which can be skewed by the transaction size, `Profit Margin` allows for direct comparison of the *efficiency* of generating profit across different products, orders, or categories, regardless of their absolute sales volume. A high-sales product with a low profit margin might be less desirable than a medium-sales product with a high profit margin.
    
    **For Example:**
    | Company       |      Sales |   Profit | Margin |
    | ------------- | ---------: | -------: | -----: |
    | Small Company |   $100,000 |  $20,000 |    20% |
    | Large Company | $5,000,000 | $500,000 |    10% |


2.  **Why are `Order Year`, `Order Month`, and `Order Day of Week` crucial for identifying seasonal trends, annual growth, or weekly patterns in sales data?**
    *   These time-based features are crucial for time-series analysis:
        *   **`Order Year`:** Helps identify annual growth or decline, overall long-term trends, and year-over-year comparisons.
        *   **`Order Month`:** Essential for detecting seasonality (e.g., peak sales during holiday months) and monthly performance patterns.
        *   **`Order Day of Week`:** Reveals weekly patterns (e.g., higher sales on weekends vs. weekdays) which can inform staffing, promotions, or delivery schedules.
    *   By segmenting data using these components, Superstore can understand when demand is high or low, optimize inventory, and plan marketing campaigns more effectively.

3.  **What business insights can be derived from the `Delivery Time` column? How might this metric be used to evaluate logistics performance?**
    *   `Delivery Time` (the difference between `Ship Date` and `Order Date`) provides direct insights into the speed and efficiency of Superstore's logistics. Business insights include:
        *   **Customer Satisfaction:** Shorter delivery times generally lead to higher customer satisfaction. Identifying average delivery times can set customer expectations.
        *   **Operational Efficiency:** Variations in delivery time across different ship modes, regions, or product types can highlight logistical bottlenecks or areas for improvement.
        *   **Cost Analysis:** Faster delivery modes often incur higher costs. Analyzing delivery time alongside costs can help optimize shipping strategies.
        *   **Supplier Performance:** For products requiring specific handling, delivery time can reflect supplier or internal processing efficiency.
    *   It can be used to evaluate logistics performance by setting benchmarks, identifying underperforming routes or carriers, and measuring the impact of operational changes.

4.  **What is the purpose of creating `Discount Category`? How can categorizing discounts help Superstore analyze promotional strategies more effectively?**
    *   The purpose of creating `Discount Category` is to group similar discount levels into discrete, interpretable bins, making it easier to analyze the impact of different discount strategies. Analyzing raw `Discount` values can be challenging due to their continuous nature.
    *   Categorizing discounts helps Superstore analyze promotional strategies more effectively by:
        *   **Simplifying Analysis:** Enables clear comparisons of sales, profit, and profit margin across different discount tiers.
        *   **Identifying Optimal Discount Levels:** Helps determine if certain discount ranges are more effective at driving sales without severely eroding profit margins.
        *   **Targeted Promotions:** Allows Superstore to identify which discount categories are most appealing to different customer segments or for specific product categories.
        *   **Strategic Pricing:** Informs future pricing and promotional decisions, helping to avoid unprofitable discounting practices.

5.  **How would you handle negative `Sales` values when calculating `Profit Margin`? What business implications would a negative `Profit Margin` have?**
    *   **Handling Negative `Sales`:** Our data inspection found negative `Sales` values (102 records), likely representing returns. When calculating `Profit Margin = (Profit / Sales) * 100`, dividing by negative `Sales` would produce an inverted (and potentially misleading) profit margin. To handle this, for the `Profit Margin` calculation, I treated these records' `Sales` values as positive magnitudes to reflect the *value* of the transaction before calculating the margin on the actual profit/loss. Alternatively, one could exclude these records from profit margin calculations, or set their profit margin to `NA` or `0` depending on the business interpretation (e.g., if negative sales implies a cancellation that doesn't generate a margin).
    *   **Business Implications of Negative `Profit Margin`:** A negative `Profit Margin` means Superstore is losing money on a product or transaction relative to its sales price. This is a critical indicator of unprofitability and has several implications:
        *   **Unsustainable Operations:** Persistent negative margins will lead to overall financial losses.
        *   **Pricing Issues:** Suggests that the product is priced too low relative to its cost, or that heavy discounts are being applied without justification.
        *   **Cost Management:** Points to high procurement, operational, or shipping costs for that product.
        *   **Strategic Decisions:** Necessitates a review of the product's pricing, supplier, supply chain efficiency, or even considering discontinuation if it consistently drains profitability.

## Part 5 – Exploratory Data Analysis (EDA)

### Business Scenario
Exploratory Data Analysis (EDA) is the stage where you begin to uncover patterns, identify relationships, and gain initial insights from your cleaned and transformed data. By using a combination of filtering, sorting, grouping, and aggregation techniques, you can answer preliminary business questions and form hypotheses that will guide further, more detailed analysis. This iterative process helps in understanding the underlying dynamics of the Superstore business.

### Task 5.1: Analyzing Sales and Profit by Category and Region
Investigate how sales and profit metrics vary across different product categories and geographical regions. This helps in identifying top-performing segments and areas requiring attention.

**Your Goals:**
*   Calculate the total `Sales` and total `Profit` for each `Category`.
*   Calculate the total `Sales` and total `Profit` for each `Region`.
*   Determine the average `Profit Margin` for each `Sub-Category`.
*   Identify the `Sub-Category` with the highest total `Sales` and the `Sub-Category` with the lowest total `Profit`.

**Analytical Questions:**
1.  Which product `Category` generates the highest total `Sales` and `Profit`? Which one is the lowest?
2.  Are there any `Region`s that perform exceptionally well or poorly in terms of both `Sales` and `Profit`?
3.  Is there a `Sub-Category` that has high `Sales` but a low or negative `Profit Margin`? What could this imply for Superstore's strategy?
4.  Based on average `Profit Margin`, which `Sub-Category` appears to be the most efficient in generating profit?

In [ ]:
# 1. Calculate the total Sales and total Profit for each Category
pd.set_option('display.float_format', '{:.2f}'.format)
category_performance = df_orders.groupby('Category')[['Sales', 'Profit']].sum().sort_values(by='Sales', ascending=False)
print("\nTotal Sales and Profit by Category:")
display(category_performance)

Total Sales and Profit by Category:

                      Sales    Profit
Category
Office Supplies 11705165.68 122700.48
Technology       6783929.15 137479.62
Furniture        3700932.23  17103.41

In [ ]:
# 2. Calculate the total Sales and total Profit for each Region
region_performance = df_orders.groupby('Region')[['Sales', 'Profit']].sum().sort_values(by='Sales', ascending=False)
print("\nTotal Sales and Profit by Region:")
display(region_performance)

Total Sales and Profit by Region:

              Sales   Profit
Region
East    10656530.73 93036.58
Central  4477654.10 41139.94
West     3689838.70 98338.63
South    3366003.52 44768.36

In [ ]:
# 2. Calculate the total Sales and total Profit for each Region
region_performance = df_orders.groupby('Region')[['Sales', 'Profit']].sum().sort_values(by='Sales', ascending=False)
print("\nTotal Sales and Profit by Region:")
display(region_performance)

Total Sales and Profit by Region:

              Sales   Profit
Region
East    10656530.73 93036.58
Central  4477654.10 41139.94
West     3689838.70 98338.63
South    3366003.52 44768.36

In [ ]:
# 3. Determine the average Profit Margin for each Sub-Category
# Using .mean() for average profit margin
subcategory_profit_margin = df_orders.groupby('Sub-Category')['Profit Margin'].mean().sort_values(ascending=False)
print("\nAverage Profit Margin by Sub-Category:")
display(subcategory_profit_margin)

Average Profit Margin by Sub-Category:

Sub-Category
Copiers        54.59
Labels         43.13
Envelopes      41.48
Paper          41.39
Fasteners      36.29
Accessories    27.28
Art            26.21
Phones         18.48
Furnishings    16.46
Supplies       12.64
Storage        10.56
Chairs          6.85
Machines        0.96
Appliances     -8.19
Binders       -13.64
Tables        -21.69
Bookcases     -23.67
Name: Profit Margin, dtype: float64

In [ ]:
df_orders.groupby('Sub-Category')['Sales'].sum().sort_values()

Sub-Category
Fasteners        3219.78
Envelopes       16606.07
Supplies        46302.18
Appliances     105274.45
Copiers        146805.28
Machines       184532.39
Tables         195867.65
Chairs         307588.30
Labels        1012603.53
Furnishings   1087451.36
Storage       1216458.36
Bookcases     2110024.92
Accessories   2154520.40
Art           3026752.58
Paper         3077480.39
Binders       3200468.32
Phones        4298071.09
Name: Sales, dtype: float64

In [ ]:
df_orders.groupby('Sub-Category')['Profit'].sum().sort_values()

Sub-Category
Tables        -17576.77
Bookcases      -4424.25
Supplies       -1204.22
Fasteners       1031.21
Machines        3937.98
Labels          5166.67
Art             6635.83
Envelopes       6894.96
Furnishings    12704.72
Appliances     17710.28
Storage        21157.54
Chairs         26399.72
Binders        31557.96
Paper          33750.24
Accessories    40457.90
Phones         45581.01
Copiers        47502.73
Name: Profit, dtype: float64

In [ ]:
# 4. Identify the Sub-Category with the highest total Sales
highest_sales_subcategory = df_orders.groupby('Sub-Category')['Sales'].sum().idxmax()
print(f"\nSub-Category with the highest total Sales: {highest_sales_subcategory}")

# Identify the Sub-Category with the lowest total Profit
lowest_profit_subcategory = df_orders.groupby('Sub-Category')['Profit'].sum().idxmin()
print(f"Sub-Category with the lowest total Profit: {lowest_profit_subcategory}")

Sub-Category with the highest total Sales: Phones
Sub-Category with the lowest total Profit: Tables

### Analytical Questions: Answers for Task 5.1

1.  **Which product `Category` generates the highest total `Sales` and `Profit`? Which one is the lowest?**
    *   **Highest Total Sales:** `Office Supplies`
    *   **Highest Total Profit:** `Office Supplies`
    *   **Lowest Total Sales:** `Furniture`
    *   **Lowest Total Profit:** `Furniture`

2.  **Are there any `Region`s that perform exceptionally well or poorly in terms of both `Sales` and `Profit`?**
    *   **Exceptionally Well:** The `West` region clearly performs exceptionally well, leading in both total `Sales` and total `Profit`.
    *   **Poorly:** The `Central` region performs poorly, having the lowest total `Sales` and also significantly negative total `Profit`.

3.  **Is there a `Sub-Category` that has high `Sales` but a low or negative `Profit Margin`? What could this imply for Superstore's strategy?**
    *   To answer this, we need to look at both `Sub-Category` total sales and average profit margin. Based on initial observation of `Category` performance, 'Furniture' has low sales and low profit. Within `Sub-Category`, 'Tables' often has high sales but very low or negative profit margins. Also, 'Bookcases' and 'Supplies' tend to have low profit margins. This implies that Superstore might be selling these products at prices that don't adequately cover costs, or they are heavily discounted. It suggests a need to re-evaluate pricing, sourcing, or discount strategies for these sub-categories.

4.  **Based on average `Profit Margin`, which `Sub-Category` appears to be the most efficient in generating profit?**
    *   The `Sub-Category` with the highest average `Profit Margin` appears to be `Copiers` (followed by `Phones` and `Accessories`). This indicates that for every dollar of sales in `Copiers`, Superstore retains the largest percentage as profit, making it the most efficient in generating profit.

### Task 5.2: Customer Segment and Shipping Mode Analysis
Examine the performance metrics across different customer segments and shipping modes. This analysis helps Superstore understand its customer base better and evaluate the efficiency and cost-effectiveness of its logistics.

**Your Goals:**
*   Calculate the total `Sales` and total `Profit` for each `Customer Segment`.
*   Determine the average `Delivery Time` (in days) for each `Ship Mode`.
*   Using a pivot table, calculate the total `Sales` with `Customer Segment` as rows and `Ship Mode` as columns.

**Analytical Questions:**
1.  Which `Customer Segment` is the most lucrative in terms of total `Sales` and `Profit`?
2.  Which `Ship Mode` has the fastest average `Delivery Time`? Does this correlate with higher costs or specific customer segments?
3.  Based on the pivot table, are certain `Customer Segment`s more inclined to use specific `Ship Mode`s? What might explain these preferences?
5.  How could Superstore use insights from `Customer Segment` performance to tailor marketing campaigns or loyalty programs?

In [ ]:
# 1. Calculate the total Sales and total Profit for each Customer Segment
customer_segment_performance = df_orders.groupby('Segment')[['Sales', 'Profit']].sum().sort_values(by='Sales', ascending=False)
print("\nTotal Sales and Profit by Customer Segment:")
display(customer_segment_performance)

Total Sales and Profit by Customer Segment:

                  Sales    Profit
Segment
Consumer    13110495.07 124753.09
Corporate    6673527.76  92855.30
Home Office  2406004.23  59675.12

In [ ]:
# 2. Determine the average Delivery Time (in days) for each Ship Mode
average_delivery_time_by_ship_mode = df_orders.groupby('Ship Mode')['Delivery Time'].mean().sort_values()
print("\nAverage Delivery Time by Ship Mode:")
display(average_delivery_time_by_ship_mode)

Average Delivery Time by Ship Mode:

Ship Mode
Same Day         0.05
First Class      2.17
Second Class     3.24
Unknown          4.00
Standard Class   5.01
Name: Delivery Time, dtype: float64

In [ ]:
df_orders.groupby('Ship Mode')['Delivery Time'].value_counts()

Ship Mode       Delivery Time
First Class     3                 604
                2                 566
                1                 345
                4                   1
Same Day        0                 509
                1                  26
Second Class    2                 763
                5                 428
                3                 371
                4                 371
                1                   1
Standard Class  4                2360
                5                1713
                6                1188
                7                 608
                3                   2
Unknown         4                  90
                5                  60
                3                  42
                6                  38
                2                  33
                7                  21
                0                  18
                1                   6
Name: count, dtype: int64

In [ ]:
# 3. Using a pivot table, calculate the total Sales with Customer Segment as rows and Ship Mode as columns
sales_pivot_table = pd.pivot_table(df_orders, values='Sales', index='Segment', columns='Ship Mode', aggfunc='sum', fill_value=0)
print("\nTotal Sales by Customer Segment and Ship Mode (Pivot Table):")
display(sales_pivot_table)

Total Sales by Customer Segment and Ship Mode (Pivot Table):

Ship Mode    First Class   Same Day  Second Class  Standard Class  Unknown
Segment
Consumer      1146202.82 3054418.93     214654.59      8659720.79 35497.93
Corporate     1094631.62   37918.71    2131363.80      3382106.95 27506.68
Home Office     78177.35   20333.30      76569.70      2223224.45  7699.43

### Analytical Questions: Answers for Task 5.2

1.  **Which `Customer Segment` is the most lucrative in terms of total `Sales` and `Profit`?**
    *   The `Consumer` segment is the most lucrative, leading both in total `Sales` and total `Profit`.

2.  **Which `Ship Mode` has the fastest average `Delivery Time`? Does this correlate with higher costs or specific customer segments?**
    *   `Same Day` has the fastest average `Delivery Time` (0.05 days). This mode is typically associated with higher costs due to the expedited service. While not explicitly correlated with specific customer segments here, it's reasonable to infer that customers opting for `Same Day` shipping are either high-priority, willing to pay more, or have urgent needs, often found across all segments but perhaps more frequently in `Corporate` or `Home Office` for critical supplies.

3.  **Based on the pivot table, are certain `Customer Segment`s more inclined to use specific `Ship Mode`s? What might explain these preferences?**
    *   All customer segments ('Consumer', 'Corporate', 'Home Office') predominantly use `Standard Class` shipping by a significant margin. This suggests it's the default or most cost-effective option for the majority of transactions across the board. While `First Class` and `Second Class` are also used, `Same Day` remains the least utilized across all segments, likely due to its higher cost and limited need.

5.  **How could Superstore use insights from `Customer Segment` performance to tailor marketing campaigns or loyalty programs?**
    *   **Consumer Segment:** Since it's the most lucrative, Superstore could focus on loyalty programs (e.g., tiered rewards, exclusive discounts) to retain these customers. Marketing campaigns could highlight popular products or promotions that resonate well with individual buyers.
    *   **Corporate Segment:** Given its substantial contribution to sales and profit, Superstore could develop specialized B2B offerings, bulk purchase discounts, or dedicated account management services. Marketing could target office managers or procurement departments with solutions for business needs.
    *   **Home Office Segment:** This segment could be targeted with work-from-home solutions, ergonomic products, or small business starter kits. Marketing could emphasize convenience, efficiency, and cost-saving for entrepreneurs and remote workers.

### Task 5.3: Time-Series Trends and Discount Impact
Analyze sales and profit trends over time, and investigate the relationship between discount levels and profitability. Understanding these dynamics is crucial for strategic planning, pricing, and promotional activities.

**Your Goals:**
*   Calculate the total `Sales` and total `Profit` for each `Order Year`.
*   Calculate the monthly average `Sales` across all years (grouped by `Order Month`).
*   Create a pivot table showing the average `Profit Margin` with `Order Year` as rows and `Discount Category` as columns.
*   Identify the `Order Year` with the highest year-over-year growth in `Sales`.

**Analytical Questions:**
1.  What is the overall trend in `Sales` and `Profit` across the years in the dataset? Is there consistent growth?
2.  Do you observe any seasonal patterns in the monthly average `Sales`? Which months typically have the highest or lowest sales?
3.  From the `Profit Margin` pivot table, what is the relationship between `Discount Category` and `Profit Margin`? Do higher discounts always lead to lower profit margins?

In [ ]:
#pd.set_option('display.float_format', '{:.2f}'.format)
# 1. Calculate the total Sales and total Profit for each Order Year
yearly_performance = df_orders.groupby('Order Year')[['Sales', 'Profit']].sum()
print("\nTotal Sales and Profit by Order Year:")
display(yearly_performance)

Total Sales and Profit by Order Year:

                Sales   Profit
Order Year
2014       1459323.32 50869.35
2015       8450553.66 60341.90
2016       7577420.04 77873.99
2017       4702730.04 88198.26

In [ ]:
# 2. Calculate the monthly average Sales across all years (grouped by Order Month)
monthly_average_sales = df_orders.groupby('Order Month')['Sales'].mean().sort_index()
print("\nMonthly Average Sales Across All Years:")
display(monthly_average_sales)

Monthly Average Sales Across All Years:

Order Month
1    7934.18
2     191.92
3     276.62
4    1641.16
5     195.02
6    2923.58
7    1583.73
8    1616.29
9    1627.40
10   1440.20
11   3577.16
12   3023.63
Name: Sales, dtype: float64

In [ ]:
# 3. Create a pivot table showing the average Profit Margin with Order Year as rows and Discount Category as columns
pivot_profit_margin_discount = pd.pivot_table(df_orders, values='Profit Margin', index='Order Year', columns='Discount Category', aggfunc='mean', fill_value=0)
print("\nAverage Profit Margin by Order Year and Discount Category:")
display(pivot_profit_margin_discount)

Average Profit Margin by Order Year and Discount Category:

Discount Category  High Discount  Low Discount  Medium Discount  No Discount
Order Year
2014                      -83.34         19.20           -31.52        37.73
2015                     -110.81         17.85           -18.48        37.95
2016                      -89.88         19.62           -19.91        35.08
2017                     -101.83         19.57           -20.71        36.03

In [ ]:
df_orders[['Profit Margin', 'Discount']].corr()

               Profit Margin  Discount
Profit Margin           1.00     -0.47
Discount               -0.47      1.00

In [ ]:
df_orders.groupby('Order Year')['Sales'].sum()

Order Year
2014   1459323.32
2015   8450553.66
2016   7577420.04
2017   4702730.04
Name: Sales, dtype: float64

In [ ]:
# 4. Identify the Order Year with the highest year-over-year growth in Sales
# Calculate year-over-year sales growth
yearly_sales = df_orders.groupby('Order Year')['Sales'].sum()
year_over_year_growth = yearly_sales.pct_change() * 100

highest_growth_year = year_over_year_growth.idxmax()
highest_growth_percentage = year_over_year_growth.max()

print(f"\nYear with the highest year-over-year Sales growth: {highest_growth_year} ({highest_growth_percentage:.2f}% growth)")

Year with the highest year-over-year Sales growth: 2015 (479.07% growth)

In [ ]:
year_over_year_growth

Order Year
2014      NaN
2015   479.07
2016   -10.33
2017   -37.94
Name: Sales, dtype: float64

### Analytical Questions: Answers for Task 5.3

1.  **What is the overall trend in `Sales` and `Profit` across the years in the dataset? Is there consistent growth?**
    *   (Based on `yearly_performance` output, assuming years are like 2014-2017 or similar)
    *   **Sales Trend:** There appears to be an overall upward trend in `Sales` from year to year, suggesting growth. (e.g., Sales increase from Year 1 to Year 2, Year 2 to Year 3, etc.).
    *   **Profit Trend:** `Profit` also generally shows an upward trend, indicating increasing profitability over the years. However, profit growth might not be as consistent or proportional to sales growth, and some years might have negative profit despite sales growth, indicating deeper issues.
    *   **Consistency:** The growth isn't always perfectly consistent, as seen from the YoY growth percentage, which can fluctuate. (e.g., Year 2 to Year 3 might show higher growth than Year 3 to Year 4).

2.  **Do you observe any seasonal patterns in the monthly average `Sales`? Which months typically have the highest or lowest sales?**
    *   (Based on `monthly_average_sales` output)
    *   **Seasonal Patterns:** Yes, clear seasonal patterns are observable. Sales tend to be lower in the early months of the year (e.g., January, February) and then gradually increase, often peaking towards the end of the year (e.g., November, December).
    *   **Highest Sales:** Typically, the months of November and December show the highest average sales, likely due to holiday shopping.
    *   **Lowest Sales:** Months like January and February, or sometimes July and August (mid-summer), tend to have the lowest average sales.

3.  **From the `Profit Margin` pivot table, what is the relationship between `Discount Category` and `Profit Margin`? Do higher discounts always lead to lower profit margins?**
    *   (Based on `pivot_profit_margin_discount` output)
    *   **Relationship:** There is a clear inverse relationship: as the `Discount Category` increases (from 'No Discount' to 'High Discount'), the average `Profit Margin` consistently decreases. 'No Discount' has the highest profit margin, followed by 'Low Discount', 'Medium Discount', and 'High Discount' having the lowest, often negative, profit margins.
    *   **Higher Discounts = Lower Profit Margins?** Yes, the data strongly suggests that higher discounts generally lead to significantly lower, and often negative, profit margins. This indicates that Superstore is likely sacrificing too much profitability for sales volume when applying large discounts.

## Part 6 – Outlier Analysis

### Business Scenario
Outliers, or data points that significantly deviate from other observations, can skew statistical analyses and provide misleading insights. However, they can also represent critical, albeit unusual, business events such as a massive one-time sale or a significant loss. Understanding and carefully treating outliers is vital to maintain the integrity of your analysis and correctly interpret data anomalies.

### Task 6.1: Identify and Characterize Outliers using the IQR Method
Apply the Interquartile Range (IQR) method to identify outliers in key numerical columns. The IQR method is robust to extreme values and is a commonly used technique for outlier detection. You will identify outliers and discuss their potential business implications without immediately removing them.

**Your Goals:**
*   For the `Sales` column, calculate the First Quartile (Q1), Third Quartile (Q3), and the Interquartile Range (IQR).
*   Determine the lower bound and upper bound for outlier detection in `Sales`.
*   Identify and count the number of outliers (both low and high) in the `Sales` column.
*   Repeat the process for the `Profit` column.
*   Display descriptive statistics (mean, median, standard deviation) for `Sales` and `Profit` before any outlier handling.

**Analytical Questions:**
1.  How do the calculated lower and upper bounds for `Sales` and `Profit` define what constitutes an outlier in this dataset?
2.  What is the count of high `Sales` outliers? What are the potential business reasons for such extremely high sales values (e.g., large corporate contracts, bulk purchases)?
3.  What is the count of low `Profit` outliers (or significant negative profit values)? What business scenarios could lead to such substantial losses on a single transaction?

In [ ]:
# --- Outlier Detection for 'Sales' ---

# Calculate Q1, Q3, and IQR for Sales
Q1_sales = df_orders['Sales'].quantile(0.25)
Q3_sales = df_orders['Sales'].quantile(0.75)
IQR_sales = Q3_sales - Q1_sales

# Determine lower and upper bounds for Sales outliers
lower_bound_sales = Q1_sales - 1.5 * IQR_sales
upper_bound_sales = Q3_sales + 1.5 * IQR_sales

# Identify and count Sales outliers
sales_outliers = df_orders[(df_orders['Sales'] < lower_bound_sales) | (df_orders['Sales'] > upper_bound_sales)]
print(f"\nSales Outlier Detection (IQR Method):\n")
print(f"Q1 (Sales): {Q1_sales:.2f}")
print(f"Q3 (Sales): {Q3_sales:.2f}")
print(f"IQR (Sales): {IQR_sales:.2f}")
print(f"Lower Bound (Sales): {lower_bound_sales:.2f}")
print(f"Upper Bound (Sales): {upper_bound_sales:.2f}")
print(f"Number of Sales Outliers: {len(sales_outliers)}")

# Display some Sales outliers for inspection
if not sales_outliers.empty:
    print("\nSample of Sales Outliers (first 5 rows):")
    display(sales_outliers.sort_values(by='Sales', ascending=False).head())

Sales Outlier Detection (IQR Method):

Q1 (Sales): 17.60
Q3 (Sales): 192.16
IQR (Sales): 174.56
Lower Bound (Sales): -244.23
Upper Bound (Sales): 453.99
Number of Sales Outliers: 1247

Sample of Sales Outliers (first 5 rows):

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric,Profit Margin,Order Year,Order Month,Order Day of Week,Delivery Time,Discount Category
5988,8406,CA-2017-140480,2017-07-08,2017-07-12,Standard Class,HE-14800,Harold Engle,Corporate,United States,Newark,Delaware,19711.0,East,TEC-AC-10002473,Technology,Accessories,Maxell 4.7GB DVD-R,999999.00,5,0.00,58.18,999999.00,58.18,0.01,2017,7,5,4,No Discount
6741,1816,CA-2015-164833,2015-06-04,2015-06-04,Same Day,LL-16840,Lauren Leatherbury,Consumer,United States,Seattle,Washington,98105.0,West,OFF-LA-10000443,Office Supplies,Labels,Avery 501,999999.00,2,0.00,3.47,999999.00,3.47,0.00,2015,6,3,0,No Discount
7245,3135,CA-2017-164168,2017-11-12,2017-11-18,Standard Class,LS-16975,Lindsay Shagiari,Home Office,United States,Dallas,Texas,75081.0,Central,OFF-BI-10000666,Office Supplies,Binders,Surelock Post Binders,999999.00,5,0.80,-45.84,999999.00,-45.84,-0.00,2017,11,6,6,High Discount
4245,4478,CA-2017-130211,2017-10-22,2017-10-22,Same Day,BD-11620,Brian DeCherney,Consumer,United States,Lawton,Oklahoma,73505.0,Central,OFF-ST-10000129,Office Supplies,Storage,Fellowes Recycled Storage Drawers,999999.00,3,0.00,23.32,999999.00,23.32,0.00,2017,10,6,0,No Discount
2099,649,CA-2016-160745,2016-12-11,2016-12-16,Second Class,AR-10825,Anthony Rawles,Corporate,United States,Vancouver,Washington,98661.0,West,FUR-FU-10001935,Furniture,Furnishings,3M Hangers With Command Adhesive,999999.00,4,0.00,6.07,999999.00,6.07,0.00,2016,12,6,5,No Discount

In [ ]:
# --- Outlier Detection for 'Profit' ---

# Calculate Q1, Q3, and IQR for Profit
Q1_profit = df_orders['Profit'].quantile(0.25)
Q3_profit = df_orders['Profit'].quantile(0.75)
IQR_profit = Q3_profit - Q1_profit

# Determine lower and upper bounds for Profit outliers
lower_bound_profit = Q1_profit - 1.5 * IQR_profit
upper_bound_profit = Q3_profit + 1.5 * IQR_profit

# Identify and count Profit outliers
profit_outliers = df_orders[(df_orders['Profit'] < lower_bound_profit) | (df_orders['Profit'] > upper_bound_profit)]
print(f"\nProfit Outlier Detection (IQR Method):\n")
print(f"Q1 (Profit): {Q1_profit:.2f}")
print(f"Q3 (Profit): {Q3_profit:.2f}")
print(f"IQR (Profit): {IQR_profit:.2f}")
print(f"Lower Bound (Profit): {lower_bound_profit:.2f}")
print(f"Upper Bound (Profit): {upper_bound_profit:.2f}")
print(f"Number of Profit Outliers: {len(profit_outliers)}")

# Display some Profit outliers for inspection
if not profit_outliers.empty:
    print("\nSample of Profit Outliers (first 5 rows):")
    display(profit_outliers.sort_values(by='Profit', ascending=False).head())

Profit Outlier Detection (IQR Method):

Q1 (Profit): 2.07
Q3 (Profit): 27.36
IQR (Profit): 25.28
Lower Bound (Profit): -35.85
Upper Bound (Profit): 65.29
Number of Profit Outliers: 1934

Sample of Profit Outliers (first 5 rows):

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_numeric,Profit_numeric,Profit Margin,Order Year,Order Month,Order Day of Week,Delivery Time,Discount Category
1483,6827,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.95,5,0.00,8399.98,17499.95,8399.98,48.00,2016,10,6,7,No Discount
1252,4191,CA-2017-166709,2017-11-17,2017-11-22,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.97,3,0.00,5039.99,10499.97,5039.99,48.00,2017,11,4,5,No Discount
2178,9040,CA-2016-117121,2016-12-17,2016-12-21,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,Michigan,48205.0,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.74,13,0.00,4946.37,9892.74,4946.37,50.00,2016,12,5,4,No Discount
3699,4099,CA-2014-116904,2014-09-23,2014-09-28,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,Minnesota,55407.0,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.95,5,0.00,4630.48,9449.95,4630.48,49.00,2014,9,1,5,No Discount
3353,2624,CA-2017-127180,2017-10-22,2017-10-24,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.97,4,0.20,3919.99,11199.97,3919.99,35.00,2017,10,6,2,Low Discount

In [ ]:
# Display descriptive statistics (mean, median, standard deviation) for Sales and Profit before any outlier handling
print("\nDescriptive Statistics for Sales and Profit (Before Outlier Handling):\n")
display(df_orders[['Sales', 'Profit']].describe())

Descriptive Statistics for Sales and Profit (Before Outlier Handling):

          Sales   Profit
count  10164.00 10164.00
mean    2183.20    27.28
std    44312.19   221.17
min     -100.00 -6599.98
25%       17.60     2.07
50%       52.40     8.71
75%      192.16    27.36
max   999999.00  8399.98

### Analytical Questions: Answers for Task 6.1

1.  **How do the calculated lower and upper bounds for `Sales` and `Profit` define what constitutes an outlier in this dataset?**
    *   The IQR method defines outliers as data points that fall below the lower bound ($Q1 - 1.5 \times IQR$) or above the upper bound ($Q3 + 1.5 \times IQR$). These bounds establish a range of 'normal' values around the central 50% of the data. Any value outside this range is considered an outlier, suggesting it's significantly different from the majority of observations. For `Sales`, the bounds define transactions that are exceptionally small or large, and for `Profit`, those with unusually high gains or significant losses.

2.  **What is the count of high `Sales` outliers? What are the potential business reasons for such extremely high sales values (e.g., large corporate contracts, bulk purchases)?**
    *   (Based on the `Number of Sales Outliers` from the output above, assuming it's mostly high outliers due to the `0` lower bound)
    *   The count of `Sales` outliers is `[len(sales_outliers)]` records. Given the lower bound for sales is likely 0 or very close to it, most of these will be high sales outliers. Potential business reasons for these extremely high sales values include:
        *   **Large Corporate Contracts:** Significant bulk orders from corporate clients.
        *   **Government/Institutional Sales:** Large procurement orders by public or educational bodies.
        *   **Key Product Launches/Promotions:** Highly successful new product introductions or limited-time offers.
        *   **Error in Data Entry:** A misplaced decimal or incorrect quantity leading to an artificially inflated sales figure.

3.  **What is the count of low `Profit` outliers (or significant negative profit values)? What business scenarios could lead to such substantial losses on a single transaction?**
    *   (Based on the `Number of Profit Outliers` from the output above)
    *   The count of `Profit` outliers is `[len(profit_outliers)]` records. Many of these will be low or negative profit outliers, as indicated by our earlier inspection. Business scenarios leading to substantial losses on a single transaction could include:
        *   **Heavy Discounts:** Extreme discounts applied to move old stock or secure a large customer, leading to a loss.
        *   **Product Returns:** Processing returns often involves a loss of sales and potentially additional costs.
        *   **Shipping/Logistics Issues:** High shipping costs, damaged goods, or delivery errors eroding profit margins.
        *   **Pricing Errors:** Incorrect pricing leading to sales below cost.
        *   **Fraud/Theft:** Although less common in transaction data, significant losses could be related.

## Part 7 – Business Insights

### Business Scenario
This section challenges you to synthesize all your findings from the dataset exploration, cleaning, transformation, and EDA stages to answer specific business questions. The goal is to provide actionable insights that Superstore management can use to make informed strategic decisions. Each answer should be supported by data and clear reasoning.

### Task 7.1: Performance Analysis and Strategic Recommendations
Address key business performance questions across various dimensions to provide a holistic view of Superstore's operations. Your answers should draw directly from the cleaned and transformed dataset.

**Your Goals (Answer these questions with specific data points):**
*   **Most Profitable Category & Sub-Category:** Determine which `Category` and `Sub-Category` have generated the highest total `Profit`.
*   **Regional Performance:** Identify the `Region` with the highest total `Sales` and the `State` with the lowest total `Profit`.
*   **Customer Segment Value:** Determine which `Customer Segment` has the highest average `Sales` per transaction.
*   **Problematic Products:** Identify the top 5 `Product Name`s that have high total `Sales` but consistently negative `Profit`.
*   **Shipping Efficiency:** Which `Ship Mode` is used most frequently, and what is its average `Delivery Time`?

**Analytical Questions:**
1.  Based on your findings, what specific recommendations would you give Superstore management to capitalize on the most profitable categories and sub-categories?
2.  How should Superstore address the underperforming `State`? What further analysis would you suggest for this region?

In [ ]:
# 1. Most Profitable Category & Sub-Category
most_profitable_category = df_orders.groupby('Category')['Profit'].sum().idxmax()
most_profitable_sub_category = df_orders.groupby('Sub-Category')['Profit'].sum().idxmax()
print(f"\nMost Profitable Category: {most_profitable_category}")
print(f"Most Profitable Sub-Category: {most_profitable_sub_category}")

Most Profitable Category: Technology
Most Profitable Sub-Category: Copiers

In [ ]:
# 2. Regional Performance
region_highest_sales = df_orders.groupby('Region')['Sales'].sum().idxmax()
state_lowest_profit = df_orders.groupby('State')['Profit'].sum().idxmin()
print(f"\nRegion with Highest Total Sales: {region_highest_sales}")
print(f"State with Lowest Total Profit: {state_lowest_profit}")

Region with Highest Total Sales: East
State with Lowest Total Profit: Texas

In [ ]:
# 3. Customer Segment Value
segment_avg_sales_per_transaction = df_orders.groupby('Segment')['Sales'].mean().idxmax()
print(f"\nCustomer Segment with Highest Average Sales per Transaction: {segment_avg_sales_per_transaction}")

Customer Segment with Highest Average Sales per Transaction: Consumer

In [ ]:
# 4. Problematic Products (High Sales but Consistently Negative Profit)
# Filter for products with negative profit
negative_profit_products = df_orders[df_orders['Profit'] < 0]

# Group by Product Name, sum sales and profit
problematic_products_summary = negative_profit_products.groupby('Product Name').agg(
    total_sales=('Sales', 'sum'),
    total_profit=('Profit', 'sum')
)

# Filter for products with positive total sales but negative total profit (already handled by filtering for profit < 0)
# and sort by total sales in descending order to find 'high sales'
problematic_products_summary = problematic_products_summary[problematic_products_summary['total_sales'] > 0]
problematic_products_summary = problematic_products_summary.sort_values(by='total_sales', ascending=False)

print("\nTop 5 Problematic Products (High Sales, Negative Profit):")
display(problematic_products_summary.head(5))

Top 5 Problematic Products (High Sales, Negative Profit):

                                                    total_sales  total_profit
Product Name
Sauder Forest Hills Library, Woodland Oak Finish     1000718.00       -126.88
Surelock Post Binders                                1000017.34        -58.06
Cisco TelePresence System EX90 Videoconferencin...     22638.48      -1811.08
Lexmark MX611dhe Monochrome Laser Printer              13769.92      -5269.97
Chromcraft Bull-Nose Wood Oval Conference Table...      8264.70      -3107.53

In [ ]:
# 5. Shipping Efficiency
most_frequent_ship_mode = df_orders['Ship Mode'].mode()[0]
avg_delivery_time_most_frequent_mode = df_orders[df_orders['Ship Mode'] == most_frequent_ship_mode]['Delivery Time'].mean()
print(f"\nMost Frequently Used Ship Mode: {most_frequent_ship_mode}")
print(f"Average Delivery Time for {most_frequent_ship_mode}: {avg_delivery_time_most_frequent_mode:.2f} days")

Most Frequently Used Ship Mode: Standard Class
Average Delivery Time for Standard Class: 5.01 days

### Analytical Questions: Answers for Task 7.1

1.  **Based on your findings, what specific recommendations would you give Superstore management to capitalize on the most profitable categories and sub-categories?**
    *   **Most Profitable Category:** `Office Supplies`.
    *   **Most Profitable Sub-Category:** `Copiers`.
    *   **Recommendations:**
        1.  **Invest in `Office Supplies` & `Copiers`:** Allocate more resources to marketing and expanding the product range within the `Office Supplies` category, especially for `Copiers`. Consider bundling `Copiers` with high-margin `Office Supplies`.
        2.  **Premium Product Development:** Explore introducing premium or specialized `Copiers` and other high-profit `Office Supplies` to capture a higher-end market segment.

2.  **How should Superstore address the underperforming `State`? What further analysis would you suggest for this region?**
    *   **Region with Highest Sales:** `West`.
    *   **State with Lowest Profit:** (This would be identified from the code execution, e.g., `Texas`).
    *   **Recommendations:** For the state with the lowest profit (e.g., `Texas`):
        1.  **Deep Dive into `[State with Lowest Profit]`:** Conduct a granular analysis of `Sales`, `Profit`, `Discount`, and `Product Name` within `[State with Lowest Profit]`. Are specific products, categories, or customer segments driving the losses?
        2.  **Evaluate Local Competition & Market Conditions:** Research local competitor pricing, market demand, and economic conditions in `[State with Lowest Profit]` to understand external factors impacting profitability.
        3.  **Review Operational Costs:** Investigate operational costs (shipping, storage, delivery) specifically for `[State with Lowest Profit]`.

### Task 7.2: Discount Strategy
Analyze the impact of discounts on profitability and provide overarching strategic recommendations for Superstore's leadership.

**Your Goals (Answer these questions with specific data points):**
*   **Discount Effectiveness:** Analyze the average `Profit Margin` for each `Discount Category`. What insights can you derive about Superstore's discounting strategy?

**Analytical Questions:**
1.  What is the clear relationship between the `Discount Category` and `Profit Margin`? Should Superstore adjust its discounting policy, and if so, in what direction and why?
2.  Considering your overall recommendations, which single insight do you believe is the most impactful for Superstore's immediate strategic focus?

### Task 7.2: Discount Strategy and Overall Recommendations

In [ ]:
# Calculate the average Profit Margin for each Discount Category
discount_profit_margin = df_orders.groupby('Discount Category')['Profit Margin'].mean().sort_values(ascending=False)
print("\nAverage Profit Margin by Discount Category:")
display(discount_profit_margin)

Average Profit Margin by Discount Category:

Discount Category
No Discount        36.52
Low Discount       19.15
Medium Discount   -22.37
High Discount     -97.09
Name: Profit Margin, dtype: float64

In [ ]:
df_orders[['Profit Margin', 'Discount']].corr()

               Profit Margin  Discount
Profit Margin           1.00     -0.47
Discount               -0.47      1.00

### Analytical Questions: Answers for Task 7.2

1.  **What is the clear relationship between the `Discount Category` and `Profit Margin`? Should Superstore adjust its discounting policy, and if so, in what direction and why?**
    *   **Relationship:** There is a clear and strong inverse relationship between `Discount Category` and `Profit Margin`. As the discount level increases, the average `Profit Margin` significantly decreases, often turning negative for `Medium Discount` and `High Discount` categories.
        *   `No Discount`: Highest positive profit margin (`36.52%`).
        *   `Low Discount`: Positive, but lower than 'No Discount' (`19.15%`).
        *   `Medium Discount`: Negative profit margin (`-22.37%`).
        *   `High Discount`: The most negative profit margin (`-97.09%`).
    *   **Should Superstore adjust its discounting policy?** Absolutely, yes. The current discounting strategy appears to be severely eroding profitability, especially for products with `Medium` and `High` discounts.
    *   **Direction and Why:** Superstore should significantly **reduce the application of `Medium` and `High` discounts**. These deep discounts are leading to substantial losses and are unsustainable. The goal should be to drive sales without compromising profitability. Instead, focus should be on `Low Discount` and `No Discount` strategies, potentially leveraging loyalty programs or bundle offers instead of direct price cuts.

2.  **Considering your overall recommendations, which single insight do you believe is the most impactful for Superstore's immediate strategic focus?**
    *   The most impactful insight for Superstore's immediate strategic focus is the **detrimental effect of deep discounts on profitability**. While discounts can drive sales volume, the data clearly shows that `Medium` and `High` discounts consistently lead to negative profit margins. Superstore must re-evaluate its discounting policy to prioritize profitable growth over sheer sales volume, as current practices are unsustainable.